### ISSUE TITLE
make fails with stdafx.h:73:23: fatal error: string_view: No such file or directory

### ISSUE THREAD

**Issue by arne-cl** [aardappel/treesheets#104]
Dear Wouter,

I am trying to build treesheets from the repo. I built and installed `wxWidgets 3.0.4` without
any (visible) errors, but when I try to compile treesheets, I get this error:

```
~/bin/treesheets/src $ make
g++ -DPACKAGE_VERSION=__DATE__ -std=c++17 `wx-config --cxxflags` -I ../lobster/include -I ../lobster/src   -c -o main.o main.cpp
In file included from main.cpp:2:0:
stdafx.h:73:23: fatal error: string_view: No such file or directory
 #include <string_view>
                       ^
compilation terminated.
<builtin>: recipe for target 'main.o' failed
make: *** [main.o] Error 1
```

**Comment by aardappel** [comment]
`string_view` is part of C++17, and as you can see `-std=c++17` is being passed, and apparently gcc is new enough to not complain about that flag... what version of gcc is this?

And yes, this is not a problem with wxWidgets, but with TreeSheets itself.

**Comment by arne-cl** [comment]
`gcc --version` says `gcc (Ubuntu 5.4.0-6ubuntu1~16.04.9) 5.4.0 20160609`.
I also tried it with a recent clang++ version `6.0.0 (tags/RELEASE_600/final)` with the same results:

```
arne@tiny-brick ~/bin/treesheets/src $ clang++ -DPACKAGE_VERSION=__DATE__ -std=c++17 `wx-config --cxxflags` -I ../lobster/include -I ../lobster/src   -c -o main.o main.cpp
In file included from main.cpp:2:
./stdafx.h:73:10: fatal error: 'string_view' file not found
#include <string_view>
         ^~~~~~~~~~~~~
1 error generated.

arne@tiny-brick ~/bin/treesheets/src $ clang++ -DPACKAGE_VERSION=__DATE__ -std=gnu++17 `wx-config --cxxflags` -I ../lobster/include -I ../lobster/src   -c -o main.o main.cpp
In file included from main.cpp:2:
./stdafx.h:73:10: fatal error: 'string_view' file not found
#include <string_view>
         ^~~~~~~~~~~~~
1 error generated.
```

**Comment by aardappel** [comment]
My linux install has gcc 7.2 and clang 6.0 and neither complains about this.

So maybe that file is actually missing from your system.. which would be weird though, since you should automatically get it when you install the compilers.

**Comment by aardappel** [comment]
So the fact that gcc 5.4 misses this header is apparently not very surprising:
https://stackoverflow.com/questions/43889414/how-to-include-c-17-headers-with-g-6-2-0-with-std-c17-optional-any-str

So that could probably be fixed by including <experimental/string_view> instead if gcc is below a certain version..

Still weird that it fails for you on clang though, since I have the same version.

**Comment by aardappel** [comment]
I just added this:

#if defined(__has_include) && __has_include(<string_view>)
    #include <string_view>
#else
    #include <experimental/string_view>
#endif

Which may make it compile with older gcc's. There are however other C++17 dependencies now so I can't guarantee it won't simply produce other problems. It should do fine with clang 6.0 though.
