### ISSUE TITLE
recursive select-all feature

### ISSUE THREAD

**Issue by LaCaradeculito** [aardappel/treesheets#112]
Hi.
I'am using TreeSheets for simple text editing. I must say I was trapped by my new ability to nest cells as a way to structure theoretical content. It all goes fine except for the fact that TreeSheets seems to apply recursively one point less text size to each nesting level. Usually having six of them the difference between the size of the main title and the last nested level is ridiculous to me. My questions are:
- Can this behavior be avoided or desabled?
- How can I just select-all recursively and set everything to one particular text size? (I couldn't find how to do this yet: select-all selects just the level without it's contents)

Thanks very much in advance.

**Comment by aardappel** [comment]
There's currently no way to disable the 1 point per nesting level. The text sizes you set are independent of the nesting level, so even though you can resize a whole tree with ctrl + mousewheel, this does not negate the nesting sizing behavior.
