### ISSUE TITLE
Ubuntu 16.04, awesome wm. Word left/right moves cursor only one symbol.

### ISSUE THREAD

**Issue by kv-gits** [aardappel/treesheets#116]
Command ctrl-left/right ignores words

**Comment by aardappel** [comment]
Can you be specific as to what you are doing, and what you expect? For me, ctrl + left/right jumps why whole words, as intended.

**Comment by kv-gits** [comment]
It jumps only one symbol. Expect jumping the whole word. 

I found that it may be about old ts version. Trying to build new one...it cant find wxwidgets. I placed it near the src directory.

**Comment by aardappel** [comment]
On linux you actually have to `make install` wxWidgets, please check https://github.com/aardappel/treesheets/blob/master/README.md and the wxWidgets Linux build documentation.
