### ISSUE TITLE
compilation issues on linux

### ISSUE THREAD

**Issue by iancustoica** [aardappel/treesheets#117]
Hello,

I decided to try the latest version of TS but can't seem to get it to compile. It might very well be something on my side but I would still like someone else to have a look at my errors just in case please.

I am on linux mint 18 and have compiled wxWidgets from their git, version 3.1.2
`/treesheets/src $ wx-config --release
3.1`

However as I try to compile TS I get an explosion:

[make_errors.txt](https://github.com/aardappel/treesheets/files/2879770/make_errors.txt)

I would appreciate any opinions on the matter.

Thanks,
Iancu

**Comment by aardappel** [comment]
See the first error in that list: `must use unicode version of wx libs`. According to https://github.com/aardappel/treesheets/blob/master/README.md `--enable-unicode` should not be needed as it is default, so that is odd. Try specifying it anyway?

**Comment by iancustoica** [comment]
Thanks, I had noticed that and tried to add the flag, but to no avail, it still returned errors.

I added the file in src/Makefile

`WX_CXXFLAGS=	`$(WX_CONFIG) --cxxflags --enable-unicode`

and the output is

`src $ make -j8
g++ -DPACKAGE_VERSION=__DATE__ -std=c++17 `wx-config --cxxflags --enable-unicode` -I ../lobster/include -I ../lobster/src   -c -o main.o main.cpp
g++ -DPACKAGE_VERSION=__DATE__ -std=c++17 `wx-config --cxxflags --enable-unicode` -I ../lobster/include -I ../lobster/src   -c -o lobster_impl.o lobster_impl.cpp
g++ -DPACKAGE_VERSION=__DATE__ -std=c++17 `wx-config --cxxflags --enable-unicode` -I ../lobster/include -I ../lobster/src   -c -o ../lobster/src/builtins.o ../lobster/src/builtins.cpp
g++ -DPACKAGE_VERSION=__DATE__ -std=c++17 `wx-config --cxxflags --enable-unicode` -I ../lobster/include -I ../lobster/src   -c -o ../lobster/src/compiler.o ../lobster/src/compiler.cpp
g++ -DPACKAGE_VERSION=__DATE__ -std=c++17 `wx-config --cxxflags --enable-unicode` -I ../lobster/include -I ../lobster/src   -c -o ../lobster/src/file.o ../lobster/src/file.cpp
g++ -DPACKAGE_VERSION=__DATE__ -std=c++17 `wx-config --cxxflags --enable-unicode` -I ../lobster/include -I ../lobster/src   -c -o ../lobster/src/lobsterreader.o ../lobster/src/lobsterreader.cpp
g++ -DPACKAGE_VERSION=__DATE__ -std=c++17 `wx-config --cxxflags --enable-unicode` -I ../lobster/include -I ../lobster/src   -c -o ../lobster/src/platform.o ../lobster/src/platform.cpp
g++ -DPACKAGE_VERSION=__DATE__ -std=c++17 `wx-config --cxxflags --enable-unicode` -I ../lobster/include -I ../lobster/src   -c -o ../lobster/src/vm.o ../lobster/src/vm.cpp
  *** Error: Unrecognised option: '--enable-unicode'
Use wx-config --help for information on command line options.
  *** Error: Unrecognised option: '--enable-unicode'
Use wx-config --help for information on command line options.
  *** Error: Unrecognised option: '--enable-unicode'
Use wx-config --help for information on command line options.
  *** Error: Unrecognised option: '--enable-unicode'
Use wx-config --help for information on command line options.
  *** Error: Unrecognised option: '--enable-unicode'
Use wx-config --help for information on command line options.
  *** Error: Unrecognised option: '--enable-unicode'
Use wx-config --help for information on command line options.
  *** Error: Unrecognised option: '--enable-unicode'
Use wx-config --help for information on command line options.
  *** Error: Unrecognised option: '--enable-unicode'
Use wx-config --help for information on command line options.`

Could you maybe tell me on which distro you last tested a 'nix compilation? I tried making a fresh linux mint 18.3 vm with build-essential and wxWidgets 3.1.2 compiled and still ran into the same issues...

**Comment by aardappel** [comment]
You can't pass `--enable-unicode` as a compiler flag, it is a flag to their configure script.
Follow the steps here: https://wiki.wxwidgets.org/Compiling_and_getting_started

**Comment by iancustoica** [comment]
Hi, Ok so I recompiled wxWidgets passing the `--enable-unicode` flag and then tried recompiling treesheets but nothing has changed.

**Comment by aardappel** [comment]
@iancustoica if nothing has changed, does that mean the first error is still this one, like above?

```
myapp.h:33:10: error: #error "must use unicode version of wx libs to ensure data integrity of .cts files"
         #error "must use unicode version of wx libs to ensure data integrity of .cts files"
          ^
```

If so, whatever you did to compile and install the wxlibs either didn't work, or it is still picking up a different set of wxlibs in your system, or something. But that's hard to tell from here without more information.

Maybe try running this command with various options to see if you can discover if it is all installed correctly: https://wiki.wxwidgets.org/Wx-Config

**Comment by 573** [comment]
Using [Nix](https://nixos.org/nix/download.html) it was as easy as:  
`nix-shell '<nixpkgs>' -p wxGTK31`  
And following the README's instructions for compiling on Linux.

**Comment by iancustoica** [comment]
thank you both for your answers. By using the above nix-shell I was able to compile everything on a fresh new virtual machine.
