### ISSUE TITLE
The program crashes when a cell with subcells inside is moved with mouse to another place

### ISSUE THREAD

**Issue by cndmn** [aardappel/treesheets#123]
When I try to move a cell with some subcells inside with my mouse to another place, then the program is always crashing. If i do it with menu > selection > move cells, it works fine. Can it be fixed?
system: win 7 32bit

**Comment by aardappel** [comment]
Can you be very exact about the actions you take? Based on the tutorial file?

There is no way to "move" cells with the mouse, so I don't understand. If I select a cell with subcells, then try to drag it elsewhere, it simply increases my selection, as intended.

**Comment by cndmn** [comment]
Move with CTRL key, like in step 12 of the tutorial.
In my case, the main cell is divided into two parts by the grid, and in one grid cell or side, the left one, for example, I create a new subcell with F9. Then I try to drag the left cell with this subcell inside to the right side, as in example 12, using the CTRL-left mouse on the selected left side, and then everything crashes. But with CTRL LEFT arrow and the same menu function it all works correctly.

**Comment by aardappel** [comment]
I tried ctrl-dragging in this situation, any many other random ones, but I don't get it to crash :(

Can you try try describing an even more precise reproducable crash? Try loading the tutorial file (F1) so that we both have the exact same file, then tell me what exactly to click on, or from where to where to drag to make it crash.

**Comment by cndmn** [comment]
Here is a video of my actions before the crash: https://youtu.be/3EzbuzbupIs
Maybe a problem with my system?

**Comment by aardappel** [comment]
Thanks for the video! It helped me reproduce the crash, in particular, it only happens if the drag is done on the top level grid.

I added a fix to the code here: https://github.com/aardappel/treesheets/commit/c65786dd004feca55a3a7ce16f77f8709ca68733

I also updated the Windows installer on the website. Give it a go and see if it works for you!

**Comment by cndmn** [comment]
It's solved! But I found another problem like that, please check it out: https://youtu.be/5X5AESDbzxw

**Comment by aardappel** [comment]
You seem to select the cell that has the subcell with the 2 in it, then ctrl + drag that cell to the one adjacent to its parent. I don't get a crash when I do that.. I think I am doing the exact same thing as in the video. Are you sure this is with the latest installer?

**Comment by cndmn** [comment]
Pretty weird situation! I will try to explain the difference between these cases as I see them.
In the first case, I did not move a whole cell, but half (with a subcell inside). In place of the other half, on the same level. And it caused a error. But after the update it stopped crashing. But the result that followed these actions led to what should have happened in the second case, that is, the movement leads to the base level of the grid, instead of moving from left to right inside the split cell.
Then I tried the second case (the second video), when moving the half (with a subcell) goes to the base grid level with a CTRL click, and it caused the same error as it was originally in the first!
It may help if you try to do both actions in the same document. Just make sure you have more cells inside the split cell (which is itself inside the frame of the basic grid), and move exactly one of the halves of the split cell as in the video. Sorry to waste your time, if so!

**Comment by aardappel** [comment]
No, thanks for sticking with me! I did manage to find it and fix it, the ctrl+drag functionality apparently had never been properly tested on this kind of situation before. Try re-installing.

https://github.com/aardappel/treesheets/commit/5744de06b1eadb84baa3c6a04c1cb5b21c7b6163

**Comment by cndmn** [comment]
Now it works fine. Thanks for your support!
