### ISSUE TITLE
request :  shortcut key for typewriter mode

### ISSUE THREAD

**Issue by kenfhill84083** [aardappel/treesheets#124]
I am starting to use Treesheets for text-memorization flashcards.  I use a system of initials representing the words I'm trying to memorize (as explained [here](http://www.productivity501.com/how-to-memorize-verbatim-text/294/)).

Typewriter mode is useful for displaying initials vs a sans serif font (which I prefer for the original text).  So I want one column to be sans serif and another column to be typewriter (Courier, it looks like).

But it would be a lot easier if there was a **shortcut key assigned to typewriter mode**.

Thanks.

**Comment by aardappel** [comment]
That's very easy to do with Options -> Change key bindig.. find the typewiter menu option, enter e.g. `CTRL+ALT+t` as the shortcut, restart treesheets.

I also added that as default: https://github.com/aardappel/treesheets/commit/ac5a36fe076c7e73131e2092d438d91fdc7500ad

**Comment by kenfhill84083** [comment]
Thanks for that good info.  And thanks for the quick response.
