### ISSUE TITLE
<disregard> feature request .  make color shown in cell, text, border color controls apply when click in the control

### ISSUE THREAD

**Issue by kenfhill84083** [aardappel/treesheets#126]
<this can be disregarded>
As it is now, to apply a color to a cell, text, or cell border, I have to click the dropdown and select a color.

It would be very useful to me if I could just click in the control, to the left of the dropdown, and apply the color currently showing in the control.  I often apply the same color to multiple cells, text, border -- all within a few seconds.  Several of the programs I use have this functionality and is very handy.

Is there a way to do this that I'm not seeing?  If not, that's why I'm making this a feature request.

Thanks.

**Comment by kenfhill84083** [comment]
Sorry,  I found the info I need on the google group.  Please disregard.  Thanks.

**Comment by aardappel** [comment]
You can close the issue in that case :)
