### ISSUE TITLE
Extension .cts is not automatically added when saving a new file

### ISSUE THREAD

**Issue by sphh** [aardappel/treesheets#127]
I use TreeSheets Sep 22 2018 on an up-to-date Linux Mint 19.1 Cinnamon 4.0.10.

When I create and save a new file, I have to add the extension `.cts` manually to the file name. All other programs I know, I can simply type the name and – if I have not supplied any extension at all –, the program adds the right extension automatically.

Example:

1. `File > New`
2. `File > Save` or `File > Save as`
3. Enter `My new file` in the `Name` field of the save dialog box and press `Save`.
4. The file is saved as `My new file` and not `My new file.cts`, which I would expect.

**Comment by aardappel** [comment]
This works on Windows, where `wxFileSelector` automatically adds the extension in this case. I guess the GTK version doesn't. I'll add code to do this manually.

**Comment by aardappel** [comment]
Fixed here: https://github.com/aardappel/treesheets/commit/94199ee92f2e14379061fc21daa0ed191ed6a58e

**Comment by sphh** [comment]
Great. Thanks.
