### ISSUE TITLE
[Feature] [Request] Hyperlinks must be clickable

### ISSUE THREAD

**Issue by n3h3m** [aardappel/treesheets#129]
Ignore this if already in progress, I would love to see the http[s]:// links could be clickable also copy-able either directly or by holding Ctrl/Cmd keys

**Comment by aardappel** [comment]
If I made them clickable, then that would interfere with the editing functionality I think. I'd at least have to make it ctrl+click or something. Though frankly just pressing F5 is fast enough for me.

Why would copying a link be different from copying any other text?

**Comment by edmundlaugasson** [comment]
Would suggest to add that feature as configurable option for those who prefer it. At the same time there might be situations when F5 does not work (#151 ) - therefore such feature would be a good opportunity to compensate such situations.

**Comment by JBlaschke** [comment]
Nice! I didn't know about hitting F5. Works on ubuntu with the latest release.
