### ISSUE TITLE
Progress to the right cell when editing?

### ISSUE THREAD

**Issue by sphh** [aardappel/treesheets#139]
When I edit a cell and I press `Enter`, the 'cursor' selects the grid line **below** the current cell. Is there a way to select the grid line **right** of the current cell?

I often tend to fill the cells column by column working my way from left to right. At the moment I have to press `Enter`, `Up` and `Right` to get to the cell right of the current cell …

**Comment by aardappel** [comment]
no key for that yet.. maybe we do can alt-enter or similar for that?

**Comment by sphh** [comment]
I just noticed, that `TAB` and `Shift+TAB` moves the selection to the right and left cell.

**Comment by sphh** [comment]
Sorry, I have to re-open this issue. Jumping to the cell right or left of the current is only working, if there is a cell right or left. If the selected and edited cell is on the very border, `TAB` would not select the grid line.

Maybe instead of using `Alt+Enter` or similar, it might be better to change the behaviour of the `TAB` (and `Shift+Tab` to select the grid line instead of jumping to the next cell. Then the behaviour of the `TAB` key would be very similar to the `Enter` key.

**Comment by aardappel** [comment]
Yeah that should be easy to change..

**Comment by aardappel** [comment]
TAB currently never select grid-lines, it merely steps thru all the cells, and also goes into edit mode. So making an exception to that and make it go to the outer grid line only for the last cell would be a bit inconsistent. In fact, to make that fully useful, it should then stop on the right outer grid line followed by the left one. That would be a bit weird.

So I think if we want the equivalent of enter going to the gridline below also to the right, it should be a different key.

**Comment by sphh** [comment]
You are right, this would be a bit weird.

What I meant, was that `TAB` should behave horizontally like `Enter` does vertically! Or very similar at least: `TAB` should select the grid line right of the current cell or the cell right of the currently selected grid line. So instead of going to the next cell, `TAB` could also select the grid line in between. `Shift+TAB` would go to the previous grid line or cell.

What do you think?

**Comment by aardappel** [comment]
I don't think changing the behavior of TAB would be good for current users that are used to it. They'd need twice as many keystrokes to navigate.

**Comment by sphh** [comment]
Yes, tabbing twice is the draw-back! IMHO the advantages outweigh the disadvantages. Which key do you have in mind?

I just played with the arrow keys. They also show a non-consistent behaviour:

-  Pressing the `Right` key moves to the next grid line or cell. In edit mode and being at the end of the text it does nothing.
- Pressing the `Down` key moves to the next grid line or cell. In edit mode and being in the last line, it also moves to the next grid line.

**Comment by aardappel** [comment]
ALT+ENTER would seem pretty natural to me.

Right not exiting edit mode is by design, since left/right are very frequent keystrokes, and accidentally exciting edit mode would be common.

**Comment by se3142** [comment]
Is this issue resolved now?
