### ISSUE TITLE
Malicious code detected by VirusTotal

### ISSUE THREAD

**Issue by oldcastlehq** [aardappel/treesheets#143]
Hi,

VirusTotal detected **Malicious.moderate.ml.score** on Windows file. Any idea why?

Thanks,
Castle

**Comment by aardappel** [comment]
Because detecting a virus is a very inexact science, and virus checkers tend to err on the side of assuming it is a virus when they see executables they don't see very often - like TreeSheets.

If you don't have strong reasons to be using VirusTotal, I recommend using Windows Defender instead.

**Comment by oldcastlehq** [comment]
Cool. Thanks.
