### ISSUE TITLE
Windows 64bit version?

### ISSUE THREAD

**Issue by oldcastlehq** [aardappel/treesheets#144]
Do you plan to release a win 64bit version for download?

**Comment by aardappel** [comment]
The current Windows download on http://strlen.com/treesheets/ is 64-bits. In fact, I am discontinuing 32-bit builds entirely, on all 3 platforms :)

**Comment by oldcastlehq** [comment]
Hummm... it's still a 32bit

![image](https://user-images.githubusercontent.com/20318144/67649272-ed9f4b00-f96a-11e9-8ea8-63a6590f5bfa.png)

**Comment by aardappel** [comment]
The exe is 64-bit, I just had not noticed that the installer needed updating to specifically install in the 64-bit dirs: https://github.com/aardappel/treesheets/commit/c1f0f58238e78193e49ef3daf86112b65482d66e

Try the new installer. Might want to de-install the old one first.

**Comment by oldcastlehq** [comment]
OK. Thanks!
