### ISSUE TITLE
Export to HTML (Tables & Styling): No lines between grid cells

### ISSUE THREAD

**Issue by mrcancer91** [aardappel/treesheets#146]
Hi, 

Just upgraded to Windows 10 so I have to reinstall TreeSheet, I'm using version Oct 23 2019. 
I faced a difference in exporting feature. Before, when choosing `Export -> HTML (Tables + Styling)`, the grid is rendered like this 
![image](https://user-images.githubusercontent.com/4757156/69899330-039f9180-1397-11ea-834e-a46dc8c1203b.png)

But in the version im using, the grid is rendered like this 
![image](https://user-images.githubusercontent.com/4757156/69899342-229e2380-1397-11ea-8a03-f2e98931d16d.png)
There is nothing to separate sells of the grid. The line is missing so when I paste the HTML into the email program, it's not clear. 
![image](https://user-images.githubusercontent.com/4757156/69899359-6abd4600-1397-11ea-9da3-7f1a1e004927.png)

Thank you for developing such a great tool for us!

**Comment by aardappel** [comment]
I've noticed that as well.. the exporting code hasn't changed though, so I wonder why that is.

**Comment by aardappel** [comment]
Fixed here: https://github.com/aardappel/treesheets/commit/6ed133880c0c068efc0b7fcf3b87c25c54232031

As a bonus, I also added a new "bullet points" html export :)

**Comment by mrcancer91** [comment]
@aardappel Excuse me! The latest source code version (1.0.2) I tested still have this issue.
```
Build environment: Windows 10
wxWidgets: wxWidgets-3.1.3
```
Setup installer generated by `TS_installer.nsi` can be downloaded [here](https://drive.google.com/open?id=1WdBnWMWQz6Jl3qZNbd80X_8Ud2Xuip0u)

Duy

**Comment by aardappel** [comment]
Hmm, not sure why that would be, seems to work for me. Can you see the above commit in your git history? Does it have the bullet point export?

**Comment by mrcancer91** [comment]
Sorry, my bad. The source package 1.0.2 doesn't have the commit you mentioned. 
I downloaded the continuous build src package and the output is nicely generated.

Cheers,
Duy
