### ISSUE TITLE
request for portable apps for Windows

### ISSUE THREAD

**Issue by sharuzzaman** [aardappel/treesheets#150]
Hi,

I would like to use TreeSheets for work, but my work laptop is Admin restricted.

Is it possible to release a portable version, eg. not using Installer, as it was restricted.

Thank you

**Comment by aardappel** [comment]
If you copy the installed files from some other computer, it should just work, TreeSheets doesn't require any special installation. Depending on the restrictions it may not be able to save changed preferences though, if the registry is also restricted.

**Comment by acicovic** [comment]
A portable version would be superb. Maybe considering writing settings to an .ini file (or such) would be a good idea. There are several apps that allow you to use an .ini file or the registry depending on whether you have a file named .portable (or similar) within the program's folder.

**Comment by RoyiAvital** [comment]
@aardappel , Any chance for a mode which doesn't use registry for setup but the local installation folder?

**Comment by aardappel** [comment]
I guess I wasn't aware, but this should already work: if you run `TreeSheets.exe -p` it starts up in portable mode, which writes to `TreeSheets.ini` in the current dir instead of the registry.

Also, you can get "no installer" binaries from https://github.com/aardappel/treesheets/actions

**Comment by RoyiAvital** [comment]
Could we have an official `zip` file generated for each release? With that flag we basically have a portable version.

**Comment by aardappel** [comment]
I do "releases" super infrequently or not at all.

As you can see from the main page https://strlen.com/treesheets/ there is already a link to recent "no installer" versions, you probably want those instead of some version from years ago.

**Comment by merriman-xyz** [comment]
> I guess I wasn't aware, but this should already work: if you run `TreeSheets.exe -p` it starts up in portable mode, which writes to `TreeSheets.ini` in the current dir instead of the registry.
> 
> Also, you can get "no installer" binaries from https://github.com/aardappel/treesheets/actions

Just downloaded [Windows TreeSheets (no installer)](https://github.com/aardappel/treesheets/suites/9022250609/artifacts/416178835) artifact and ran TreeSheets without issue.  Just make sure you are logged into GitHub to be able to download the artifact from the builds.

**Comment by lpagg** [comment]
Hello,
Windows - with not admin right, here.
I willing to try TreeSheets but I was not able to find the [Windows TreeSheets (no installer)] for download.
Could you please support me for the link to download?
Thanks!

**Comment by aardappel** [comment]
@lpagg there are no installers being built on every CI run as noted above, for example here: https://github.com/aardappel/treesheets/actions/runs/3809129847

**Comment by ags1234** [comment]
I would also want every release to have a portable Windows version, which can be downloaded as an archive, not an exe.

**Comment by aardappel** [comment]
@ags1234 the no-installer version we already make is a .zip, did you look?

**Comment by ags1234** [comment]
Yes, I did. I do not see a zipped Windows version.

![2023-02-14_193259](https://user-images.githubusercontent.com/21011513/218813999-5236e798-34cf-4505-9e8f-424422e51a7c.png)

**Comment by aardappel** [comment]
Try the link I posted again.

**Comment by aardappel** [comment]
Ok, updated the CI such that the no installer version also shows up on the releases page, that way its easier to find for most people.

**Comment by ags1234** [comment]
Now everyone can clearly see the portable version for Windows.


![2023-02-15_191408](https://user-images.githubusercontent.com/21011513/219103643-14f5f1d9-258e-46ba-9742-871b00e84d5b.png)
