### ISSUE TITLE
Suggestion: Separate Search / Replace dialog

### ISSUE THREAD

**Issue by mrschyte** [aardappel/treesheets#157]
Currently search & replace is shown in the toolbar. If the toolbar is disabled these functions become unavailable. I suggest to replace the toolbar functionality with a search/replace dialog the same way it is done in most applications. Apart from allowing the toolbar to be disabled, this will have the benefit of being familiar to most users.

**Comment by aardappel** [comment]
The search functionality is "instant", as you type feedback.. that wouldn't work so naturally with a dialog that's blocking part of your view. Besides, a dialog would be slower to use, so I am not a fan of them.

Then you also need a way to cancel the search, which currently just means clear the search input.

I suppose a dialog could pop up whenever the toolbar is disabled, but I'd prefer not to complicate things if not needed. Or even simpler, enable the toolbar when someone presses search, and make sure there's a keybind for disabling it again.

Why do people generally like to disable the toolbar? I had assumed its mostly for when you do a presentation or something.

**Comment by mrschyte** [comment]
I can see the appeal of having it in the toolbar. I guess my problem with it that it is a bit awkward to use at first as most applications do it using a separate dialog. I would like to disable the toolbar because I like the cleaner look and feel. The only functions I'm using from the toolbar is search and replace and the cell color stuff.

I know that you try to keep the code as minimal as possible, but if I was designing the UI I would have a separate search and replace dialog or a popup editbox similar to what Firefox has. Cell coloring could live inside a context menu or a toolbox window that only shows if you hover over the cell or something.

I think that functionality should be more localized by the context of where they are used (e.g. cell coloring). Currently all commands can be reached by either pressing the associated hotkey or browsing it out from the menu. For one-off things the menu is fine for frequently used things the hotkey is fine, but for things in the middle ground it is tedious to use the menu or to come up with a new keybinding.

Please don't take this as criticizing TS, I'm really grateful to be able to use this wonderful software. Learning how to use TS efficiently however was not easy because some of the UI decisions felt foreign to me. I think that this initial hurdle could turn users away before they could see the benefits of using TreeSheets.

**Comment by aardappel** [comment]
You are entirely right.. but at this point it isn't even about keeping code simple, it is about getting the most amount of functionality with the smallest time investment. TreeSheets is one of many projects I maintain, and not very actively.

Just checked the code, but even my idea to quickly turn on/off the toolbar is going to be more involved to make happen, as currently toolbar is only ever created on startup (or not).

So looks like for now you'll simply have to leave the toolbar on, if you want to search.
