### ISSUE TITLE
Linux build clang++-9 and g++-9 depencency issues preventing TreeSheets to start at all

### ISSUE THREAD

**Issue by edmundlaugasson** [aardappel/treesheets#161]
64-bit Ubuntu 18.04.4 LTS based LXLE 18.04 (LXDE desktop) experience - incompatible library prevents TreeSheets starting at all. This applies to Linux builds available at https://github.com/aardappel/treesheets/actions

clang++-9 and g++-9
```
./treesheets 
./treesheets: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by ./treesheets)

$ ls -l /usr/lib/x86_64-linux-gnu/libstdc++.so.6
lrwxrwxrwx 1 root root 19 March 10 14:29 /usr/lib/x86_64-linux-gnu/libstdc++.so.6 -> libstdc++.so.6.0.25

$ dpkg -l | grep libstdc
ii  libstdc++6:amd64                      8.4.0-1ubuntu1~18.04                             amd64        GNU Standard C++ Library v3
ii  libstdc++6:i386                       8.4.0-1ubuntu1~18.04                             i386         GNU Standard C++ Library v3

$ dpkg -l | grep -w libc
ii  libc++1:amd64                         6.0-2                                            amd64        LLVM C++ Standard library
ii  libc++abi1:amd64                      6.0-2                                            amd64        LLVM low level support for a standard C++ library
ii  libc-ares2:amd64                      1.14.0-1                                         amd64        asynchronous name resolver
ii  libc-bin                              2.27-3ubuntu1                                    amd64        GNU C Library: Binaries
ii  libc-dev-bin                          2.27-3ubuntu1                                    amd64        GNU C Library: Development binaries
ii  libklibc                              2.0.4-9ubuntu2                                   amd64        minimal libc subset for use with initramfs
ii  liblocale-gettext-perl                1.07-3build2                                     amd64        module using libc functions for internationalization in Perl
ii  linux-libc-dev:amd64                  4.15.0-99.100                                    amd64        Linux Kernel Headers for development
```
What can we do to solve dependencies while that library is installed but seems not compatible? Would like to use AppImage version but there hyperlinks do not work.

**Comment by aardappel** [comment]
Yeah they're built with the latest compilers on the latest ubuntu, so I am not surprised they may require a newer runtime than what some users have. Linux is just broken in this respect. I would link statically, but of course that is not well supported either.

I sit possible to `sudo apt-get install libstdc++.so.6.0.26` (maybe needs some non-standard repo to be added?)

Or use `dpkg` to install it manually? Similar to https://askubuntu.com/questions/1143268/how-to-install-a-libc6-version-2-29#_=_

**Comment by Narvey** [comment]
I found similar errors in both Debian 11 and Fedora 36 when using precompiled binaries. 

I didn't even need to manually install anything, all I had to do in Debian 11 was:
`sudo apt install treesheets`
