### ISSUE TITLE
feature request: in-cell formatting

### ISSUE THREAD

**Issue by edmundlaugasson** [aardappel/treesheets#166]
Hereby I propose the idea to allow in-cell formatting like change attributes of text inside cell and not whole cell only. This means to change e.g. bold, italic, color, size etc for one or more selected character, word only inside cell and not only the whole cell or many selected cells.

**Comment by aardappel** [comment]
There was a previous issue with discussion of this feature here: https://github.com/aardappel/treesheets/issues/121
(closing this one in favor of the existing one)
