### ISSUE TITLE
Folding(F9) replaces any Images previously there

### ISSUE THREAD

**Issue by ghost** [aardappel/treesheets#17]
Hi. In a cell that can fold(ie. has another subcell(Ins key)) which also has an image (such as the green check mark) when pressing F9 to Fold, the checkmark is replaced by a `+` icon (which is fine) but then when unfolding(F9 again) the `+` is gone and the previous image(green check mark) is not restored and thus is lost.

**Comment by nixn** [comment]
+1. it's really annoying!

**Comment by aardappel** [comment]
Just fixed this issue here: https://github.com/aardappel/treesheets/commit/0f07c5bd2a1ba5ac876a0c6a638b3471bfe64b15
Also uploaded new Windows build.

**Comment by ngirard** [comment]
@aardappel : you might want to close this issue ;-) Thanks for your work, by the way !

**Comment by aardappel** [comment]
np :)
