### ISSUE TITLE
Crash when pressing F1

### ISSUE THREAD

**Issue by dotchicken** [aardappel/treesheets#171]
Hello,
product version: Oct 23 2019 (downloaded exe)
OS version: W10 Pro 1909 (build 18363.1016)

how to reproduce:
1.) treesheets open with "C:\Program Files\TreeSheets\examples\tutorial-de.cts"
2.) press F1
3.) Errormessage: "Please send C:\Program Files\TreeSheets.exe.exp.log to the developer!"
Info: no such log-file exists (folder options set to show hidden files)

When the tutorial is not open, but other documents:
1.) pressing F1 opens the tutorial file
2.) pressing F1 again crashes as above.

edit: Forgot to mention: Any non-saved Information is lost :-(

Will add more Info if needed.
Thank you.
I'm still new to the program.

**Comment by aardappel** [comment]
Tried your exact scenario: pressing F1 with `tutorial-de.cts` open just loads `tutorial.cts`, then pressing F1 again does nothing.

Tried pressing F1 in a variety of ways, no crash.

Also tried in debug mode, no crash.

The path looks incorrect for the log file, should probably be in `C:\Program Files\TreeSheets\TreeSheets.exe.exp.log` (note the missing dir in the original path)

**Comment by aardappel** [comment]
Are you sure it said `"Please send C:\Program Files\TreeSheets.exe.exp.log to the developer!"` ? That would indicate the .exe file is in the wrong place?

**Comment by dotchicken** [comment]
My Path to the executable:
"C:\Program Files\TreeSheets\TreeSheets.exe"

My program just before pressing F1. I just noticed the path in the title (different slashes)

![treesheetsopen](https://user-images.githubusercontent.com/19369012/94371861-d5dfc200-00f9-11eb-98f5-52385cf38597.png)

After pressing F1:

![fehlermeldung](https://user-images.githubusercontent.com/19369012/94371876-f3ad2700-00f9-11eb-8001-1683b78f138b.png)


As can be seen I made an error with the first mentioned path -my bad, sorry.

**Comment by aardappel** [comment]
and that file isn't there (at the new path) ?

**Comment by aardappel** [comment]
Ok, I think I've found the problem by just looking at the code, this should fix it: https://github.com/aardappel/treesheets/commit/524ec28e58d1ab2c16e9ba943ec315dec23767c6

**Comment by dotchicken** [comment]
I have to admit, testing it will take me a while. No experience yet in building from source and will therefore need some time.
Thank you for your speedy response.

**Comment by aardappel** [comment]
You can also grab builds from here: https://github.com/aardappel/treesheets/actions (click first link in list)

**Comment by dotchicken** [comment]
Thank you for both the notice about the link and the fix.
I tested it on 3 Computers (2xWin10, 1xWin8.1) - all three had the issue fixed.
