### ISSUE TITLE
Quick edit cell

### ISSUE THREAD

**Issue by santhoshr** [aardappel/treesheets#173]
thanks for the wonderful tool, it has great idea and execution.

could you add one more option to quickly edit text in the cell when we type instead of using F2 or replacing the text entirely, this can be selectable option, so those who like to edit the usual way will still continue using it

**Comment by aardappel** [comment]
You can also use Enter to edit text btw.

How would this work? You select a sell and it immediately places a text editing cursor at the end? Note that this would affect a lot of other functionality, for example cursor keys wouldn't be able to move to neighboring cellls directly anymore, as they'd instead move inside the text.

**Comment by santhoshr** [comment]
It will not make cell editable by default, only when certain characters are typed it will start appending, e.g. can you can limit to alphabets, punctuations, whitespace characters alone to trigger automatic cell editing/appending ?

For Enter key, since it auto selects/highlights text typing without deselecting would replace text, could you add option to make enter to start text appending, or default to text selection in edit mode ?

**Comment by aardappel** [comment]
So that really is only the difference between default overwrite vs default append, since it already enters edit mode upon typing most characters.

**Comment by santhoshr** [comment]
Yes you are right, so it is between default select and default append, so one option could control both enter key as well type to edit
