### ISSUE TITLE
[Bug] Incorrect cell positioning when deleting text while using Line-Style Rendering

### ISSUE THREAD

**Issue by Kookiness** [aardappel/treesheets#177]
Win 10 64-bit
TreeSheets version Oct 23 2019

There seems to be a bug when using Line-Style Rendering (which is used by selecting cells and then pressing Alt+3 or Alt+6):

If you remove a lot of the text in a cell (or just delete that cell entirely), it results in that branch of cells being positioned incorrectly and potentially overlapping other cells.

I've copied and pasted the contents of an example project below to try to demonstrate this; just copy and paste it into a TreeSheets cell.
Please make sure to copy all of it, including the line break at the very end of the code block (which seems necessary to preserve the cell hierarchy, and also seems necessary in order for the bug to reproduce) (According to my testing, if copied and pasted correctly, you should see the cells have kept their colours (one pink and one green), though I'm not sure how they do this!):

```
dfsdf
  sfdf
    KEEP AN EYE ON THIS CELL
    This cell deliberately contains a lot of text, to make it easier to demonstrate the issue of one cell overlapping another while using Line-Style Rendering. In order to demonstrate the issue, I recommend that you make sure this entire project uses Line-Style Rendering, which is acquired by selecting all the cells in the project (easy to do by clicking on a cell and then pressing Esc a few times), and then pressing Alt+3 or Alt+6 (or going to "Edit > Layout & Render Style > [Vertical or Horizontal] Layout with Line Style Rendering"). Then, click on this cell, press Delete and see what happens (Then press Ctrl+Z/undo to continue reading); it should cause the cells connected to this one to overlap with cells in the other branch, and also note that the lines connecting this cell to its root then appear to be incorrectly positioned, at least for me. Alternatively, instead of deleting this cell, you can just edit its text to be short, and this should result in the same issue of overlapping cells. If, after deleting/editing this cell, you select everything and press Alt+3 or Alt+6, the position of the red cell will be correctly reset. Since the problem only seems to occur when using the Alt+3 or Alt+6 rendering methods, it seems that the issue relates to Line-Style Rendering.
  dsfsdfsdf
    dsfdsfdsf
    sdfdsd
    dsfdsfds
    dsfdsfdsf
    sdfdsd
    dsfdsfds
    sdsfdf
    fgdfdfdg

```

**Comment by aardappel** [comment]
Created new document, pasted your text in, selected all, alt+3, then delete on the large cell, and I get:

![image](https://user-images.githubusercontent.com/4663648/109858354-8f464480-7c10-11eb-86e3-e2c9bee221ef.png)

I don't see rendering errors at any point (also tried with partially deleting text, and alt+6). Am I missing something?

**Comment by Kookiness** [comment]
The result you got looks like the one I get if I don't copy/paste the final line break I included in the code block. Did you make sure to copy it?

I tried uploading the .cts file, but github wouldn't allow it. Should I try uploading it elsewhere?

**Comment by aardappel** [comment]
This also on Win10, though latest version. Can you download a more recent TreeSheets from e.g. https://github.com/aardappel/treesheets/actions/runs/566327704

**Comment by aardappel** [comment]
Yes, my pasted text has a line-break after `fgdfdfdg`.

If it only happens with your .cts file, then upload it somewhere.. dropbox?

**Comment by ngirard** [comment]
Or try zipping the cts file.

**Comment by Kookiness** [comment]
Thank you, I tried getting a newer version, but I couldn't manage to figure out how to download an installer from that page.

Ah, great, thank you ngirard for the idea about zipping it!

[Bug Demo - Overlapping Cells.zip](https://github.com/aardappel/treesheets/files/6079079/Bug.Demo.-.Overlapping.Cells.zip)

**Comment by aardappel** [comment]
Click on where it says `Windows TreeSheets (installer)`

**Comment by Kookiness** [comment]
Huh, okay, thank you. I tried that earlier and I didn't think it had worked, but it seems it did. Oops! My mistake.

Okay, the version I have is now from Feb 14 2021. The issue still occurs when I use the .cts file from the .zip.

**Comment by aardappel** [comment]
Ok, just created a fix: https://github.com/aardappel/treesheets/commit/d0562cc21b7a961d16268af172a2207814158f14
Also fixed a rendering issue I noticed while debugging this: https://github.com/aardappel/treesheets/commit/9ba885f847a0619758b8e79fd48e9a7eb5849735

New binaries will be up here as soon as the CI finishes building: https://github.com/aardappel/treesheets/actions/runs/619215506
