### ISSUE TITLE
Fixed Size Textbox Cell- implementing Mandala Chart, Sticky Notes, Mini Notepad etc 

### ISSUE THREAD

**Issue by santhoshr** [aardappel/treesheets#179]
Is it possible to have fixed size Text Cell for implementing Manadala Chart, Sticky Notes, etc.

The way it works is, each cell will have a defined box size, the content will scroll within the fixed size, can have nested cells, everything is as usual but unlike current options Size and Width option which controls text size and content width, the Fixed size cell is more like Container with defined height and width, the size is fixed and does not change without content or with content.

This opens up designing something like Mandala Chart, which is 9x9 grid, each cell inside grid will expand into its own 9x9 grid, it is arranged like this
F |  C  | G
B |  A |  D 
E |  A  | H

A is central idea, expands into A, B, C, D, E, F, G, H, each then expands into own grid something like mindmap but differently

examples,
http://www.activegarage.com/wordpress/wp-content/uploads/A-Chart-eMandala.png
http://www.activegarage.com/wordpress/wp-content/uploads/B-Chart-eMandala.png
http://www.activegarage.com/wp-content/uploads/SAMURAI-WALK-Concept.png
https://www.daijob.com/user/media/images/businessenglish/will/083_From_Matrix_to_Mandala_Chart.jpg

I tried to replicate it with what is available using Cell colours, but did not work
![mandala](https://user-images.githubusercontent.com/2510419/113911602-c8696a00-97f7-11eb-9b7c-c033a30aafb2.png)

**Comment by aardappel** [comment]
TreeSheets is fundamentally about automatic layout and sizing. While fixed size of a cell wouldn't be too hard to implement, allowing things to scroll inside cells would require a lot of fundamental reworking on how things work right now, and is not likely to ever happen.

While I understand that you'd want to emulate an existing concept, something being able to take up more or less space as needed, and not having to scroll, seems easier to use to me than fixed sizes and scrolling.

You can always shrink text size if a cell contains too much stuff, or if it contains way too much, use folding. You can also somewhat control the width of cells with increase/decrease column width.

**Comment by santhoshr** [comment]
I understand, trying to adapt TreeSheets for what it is not designed for and going against its fundamental design idea of flexible and nested layouts, the problem is like VIM/Emacs kind of problem, once we like something, we want to use it everywhere and every situation. I like Treesheets as an idea and implementation, and want to adapt it for wide requirements!

Thanks for the update.
