### ISSUE TITLE
[Bug] When overwriting a cell's text, its text gets resized to match the size of the text in the cell immediately below it

### ISSUE THREAD

**Issue by Kookiness** [aardappel/treesheets#180]
Win10 x64
TreeSheets Ver. Mar 3 2021

Steps to reproduce:

- Select a cell
- Shift+Mousewheel up or down to change that cell's text size
- Single-left-click on the cell immediately above that (doesn't matter if it already contains text or not)
- Start typing text into it, to overwrite its previous contents

The newly-typed text gets incorrectly resized to match the text size of the cell immediately below it.

**Comment by aardappel** [comment]
Fixed, auto sizing now only happens on new cell, not overwriting existing.
