### ISSUE TITLE
file_format_spec.txt is incomplete and covers v16 not the current v19

### ISSUE THREAD

**Issue by quag** [aardappel/treesheets#185]
The file_format_spec.txt covers v16, which is before the zlib compression was added. The current version is v19.

While writing a python parser for cts files (https://gist.github.com/quag/e219f69670cd395d4a59a392557df284) a few issues came up:

1. zlib compression is used
2. zlib compression isn't on the whole file, but only after the images (from the first root cell on)
3. timestamps are millisecond POSIX timestamps
4. endianness of encoding
5. encoding of strings
6. strings are written length prefixed – https://docs.wxwidgets.org/3.0/classwx_data_output_stream.html#ad59954476921dd0f4a480e4d212ed61a and https://github.com/wxWidgets/wxWidgets/blob/master/src/common/datstrm.cpp#L586
7. fields are added and removed between versions, and sometimes meanings changed. Pseudocode of a parser reading into a data model might be the best way to document the format

PS: For people writing parsers, I suggest you start from this line in the reader code and walk forward porting the branches and checks in your code as you follow along. https://github.com/aardappel/treesheets/blob/master/src/system.h#L247 . For writing cts files, start from https://github.com/aardappel/treesheets/blob/master/src/document.h#L178

**Comment by aardappel** [comment]
Thanks! Could you make a PR that incorporates these notes into `file_format_spec.txt` ?
