### ISSUE TITLE
Can I link to other grid in the current grid? Can I open other types of files like the image?

### ISSUE THREAD

**Issue by erhuanlnna** [aardappel/treesheets#195]
I find that, in TreeSheets, the image can be saved using its name, and then I can open the image by F4. I think it is an effecetive way to ref the image.
So, can I open other types of files like the image? Or I can associate the file type with specific programs, like the "TotalCommander" program does.
Also, I want to ref another predefined grid in the new grid. For example, I am recording my research paper list and one paper is based on something (like another book) that I record before.
Is it possible to achieve this? It is like the "Notion" app done. I know these issues may be out of the range of TreeSheets, and thanks for your wonderful program. 
It is very fast and flexible, (much faster than the Notion app), and it is more suitable for someone with one main computer. Thanks!

**Comment by aardappel** [comment]
Yes, it works with other file types too, and it simply uses the systems existing associations (on Windows, never tried on Linux/OSX).

You can refer to other cells in TreeSheets, check the tutorial for "Go To Matching Cell (F6)" functionality, and tags.

**Comment by erhuanlnna** [comment]
I got it. Thank you very much.
