### ISSUE TITLE
request: shortcut key binding to set font/cell text color

### ISSUE THREAD

**Issue by LordFoom** [aardappel/treesheets#197]
This is an amazing piece of software, thank you! 

I use colors a lot and it would be awesome if I could set the color, or trigger the color menu, with a keyboard shortcut, for text and cells. 

Totally understand if it you can't/won't,  just a wish on my part :) 

Thanks again for this amazing software.

**Comment by aeqvkec** [comment]
Me too. I've been longing for this feature for a long time.

**Comment by aeqvkec** [comment]
If there is a way to set the color of the selected text, instead of the whole cell text, treesheet will be more powerful and convenient to use. Thanks.

**Comment by aeqvkec** [comment]
I aslo want to know how to change the preset colors.
     let color_yellow = color { 1, 1, 0, 1 }
How do I edit this code to make "yellow" darker or equal RGB(255,192,0)? Thanks.

**Comment by aardappel** [comment]
@LordFoom added some options for applying the last color via keyboard, and also to open the popups in: https://github.com/aardappel/treesheets/commit/de2c8049122fa46f1c4455e18a5c36ff19410bde

![image](https://user-images.githubusercontent.com/4663648/148824443-d5380957-ba41-48ba-850d-0977f97494d9.png)

**Comment by aardappel** [comment]
@aeqvkec there is now way to only change the style of a part of a cell, this is quite fundamental in how the data is organized, so unlikely to change. Recommend instead to split up your text in more cells :)

`let color_my_yellow = color { 1, 0.75, 0, 1 }` would be equivalent to the RGB color you gave. However these colors are from the scripting language, and do not influence the preset colors in the menu directly.. those colors are actually here and currently can't be configured: https://github.com/aardappel/treesheets/blob/de2c8049122fa46f1c4455e18a5c36ff19410bde/src/main.cpp#L23-L30

You can of course use `Options -> Pick custom color` to pick your one current custom color.

**Comment by aeqvkec** [comment]
@aardappel
Thank you for explaining so clearly. :)

**Comment by LordFoom** [comment]
> @LordFoom added some options for applying the last color via keyboard, and also to open the popups in: [de2c804](https://github.com/aardappel/treesheets/commit/de2c8049122fa46f1c4455e18a5c36ff19410bde)
> 
> ![image](https://user-images.githubusercontent.com/4663648/148824443-d5380957-ba41-48ba-850d-0977f97494d9.png)

This is amazing, thank you!

**Comment by aardappel** [comment]
@aeqvkec latest builds are always automatically available on https://github.com/aardappel/treesheets/actions (click top line with a green checkmark, then scroll down to windows builds).
