### ISSUE TITLE
Issue running latest builds 

### ISSUE THREAD

**Issue by LordFoom** [aardappel/treesheets#198]
While trying to run the builds from github, I get the following error on the Linux versions, both Clang and g++:

"./treesheets: error while loading shared libraries: libjpeg.so.8: cannot open shared object file: No such file or directory"

The treesheets_linux64.tar.gz tarball works fine.

I have noticed that the tarball, treesheets_linux64.tar.gz, has a treesheets binary that is about 30mb, while the binaries from the artifacts above weigh in at about 12MB/13MB

Not sure if something is missing in the build process, or if I'm not doing something when I run locally?

Thanks again for great software!

**Comment by aardappel** [comment]
Well, it builds with whatever image `ubuntu-latest` maps to, so maybe something in that is incompatible with whatever distro you run?

Have you tried getting the file explicitly, e.g. `sudo apt-get install libjpeg-turbo8` ?

**Comment by LordFoom** [comment]
Thanks for the reply!

I'm running Fedora 34, and as far as I can tell I have that dependency installed:

```> sudo dnf install libjpeg-turbo.x86_64
Last metadata expiration check: 3:06:05 ago on Sun 16 Jan 2022 08:02:43 AM SAST.
Package libjpeg-turbo-2.0.90-3.fc34.x86_64 is already installed.
Dependencies resolved.
Nothing to do.
Complete!
```

And the headers as well:

```❯ sudo dnf install libjpeg-turbo-devel.x86_64
Last metadata expiration check: 3:09:00 ago on Sun 16 Jan 2022 08:02:43 AM SAST.
Package libjpeg-turbo-devel-2.0.90-3.fc34.x86_64 is already installed.
Dependencies resolved.
```

I dug around a bit and found this reddit suggestion: 
https://www.reddit.com/r/Lutris/comments/nrvcc3/zdoom_runner_looking_for_libjpegso8_on_fedora_34/

Which led me to this:
https://copr.fedorainfracloud.org/coprs/aflyhorse/libjpeg/

Adding the copr and then installing the libjpeg  led to a new error:
```
./treesheets: error while loading shared libraries: libjbig.so.0: cannot open shared object file: No such file or directory
```

I tried installing jbigkit and jbigkit-devel to sort the issue out , but unfortunatel   As far as I can tell, libjbig is a debian only package?

I'll keep having a go every now and then, hopefully I can find way to get it in there.

**Comment by aardappel** [comment]
Yeah, sadly I know very little about distro incompatibilities.. I wish they'd, err.. standardize :P

Or better yet, make static linking work better.

All these container formats are not the solution.

**Comment by LordFoom** [comment]
Upgraded to Fedora 35 and the latest builds work :D

New color shortcuts really make my day - thank you!

**Comment by jn64** [comment]
Hi @LordFoom, sorry to bother you, but could you say which is the latest build of Treesheets you were able to run on F35? I'm getting the same issue (no libjbig.so.0) even on F35 and with libjpeg8 from the copr.

**Comment by LordFoom** [comment]
Hi @jn64 

Looks like I actually haven't updated since Jan 10, but I took the treesheets g++ build from here: https://github.com/aardappel/treesheets/actions/workflows/build.yml

The clang build didn't work for me, but the g++ did. 

I just downloaded the g++ version from this build: https://github.com/aardappel/treesheets/actions/runs/2273540474 and it ran fine.

(Scroll to the bottom of the page).

Just a note, I actually uninstalled the copr libjpeg, literally did  not need it after upgrading Fedora version.

**Comment by jn64** [comment]
That build ae6506a does not work for me, either clang or g++. It still needs libjpeg.so.8 and libjbig.so.0, neither of which are in Fedora (or RPMFusion) repos for F35.

Can you give the output of:

- `dnf provides /usr/lib64/libjpeg.so.8`
- `dnf provides /usr/lib64/libjbig.so.0`

If either fail try `dnf provides "*/libjpeg.so.8"` or `dnf provides "*/libjbig.so.0"`

I will try a build from before Jan 10 in the meantime.
