### ISSUE TITLE
Accessible display of search highlights

### ISSUE THREAD

**Issue by despens** [aardappel/treesheets#200]
At the moment, TreeSheets highlights text on the sheet that matches input into the search box by using red type on white background.

People with a color vision deficiency ([deuteranopia and deuteranomaly](https://en.wikipedia.org/wiki/Color_blindness#Deuteranopia)) have a very hard time or won't be able to distinguish this highlighting from the default black text on white background.

I cannot see the red highlight here:
![image](https://user-images.githubusercontent.com/571494/153559254-1c8f387a-74e4-4f4d-81ae-2df2084c0952.png)

My suggestion would be instead of highlighting the matches, reducing contrast for cells that do not match (mockup):
![image](https://user-images.githubusercontent.com/571494/153559837-9515d2e6-bc84-4dde-8f5f-5227fd7c6643.png)

This "torchlight" is a very accessible way of highlighting results without reordering a list, as used for instance in Mac OS system preferences:
![image](https://user-images.githubusercontent.com/571494/153560396-3e8de7dd-9c69-4591-a89a-b3683164fa73.png)

**Comment by aardappel** [comment]
I agree that be a cool feature!

**Comment by despens** [comment]
Wow this is amazing! Thanks @t2b3 and @aardappel :pray:
