### ISSUE TITLE
copy in text edit mode does not work properly in latest builds

### ISSUE THREAD

**Issue by yrrosmi** [aardappel/treesheets#204]
Hello,
TreeSheets Version Mar 12 2022 on Windows 10 21H2

Copy selection in text edit mode(hit CTRL+C or toolbar edit/copy) and then paste in TreeSheets, it willl result in pasting the last copied cell(s), while pasting outside TreeSheets normally paste the copied text selection.

Discovered this weird behaviour yesterday then tried out different CI builds(latest and oldest available builds, both installer and no installer ones) and nothing worked.

The one on https://strlen.com/treesheets/(version Oct 23 2019) does not have this issue.

**Comment by aardappel** [comment]
Ok, I'll have a look.

**Comment by aardappel** [comment]
This should fix it, I have no idea why that worked before :)
https://github.com/aardappel/treesheets/commit/4bd2a93704ea0b38fa3e7b8fae2a8cf6f533c314

**Comment by yrrosmi** [comment]
Yes it's fixed on the latest build.
Thanks!
