### ISSUE TITLE
Find the new TS API

### ISSUE THREAD

**Issue by WangWei90** [aardappel/treesheets#215]
Hello, I want to find the new TS API. I have looked around the installed folders and website,  and want to find more information.

I think the "ts_set_border_color(col:xyzw_f)" is missing. I really like the border color.

![image](https://user-images.githubusercontent.com/20700315/163913990-6af90ade-5a0d-488c-8d2e-b1b4073d4378.png)

**Comment by WangWei90** [comment]
Can I use the `date_time_string` function here? (from lobster builtin reference)

![image](https://user-images.githubusercontent.com/20700315/163917655-af161245-aa39-4e22-b64d-5f4f942080a8.png)

**Comment by aardappel** [comment]
The function should be there.. maybe the documentation wasn't updated?

And yes, you should be able to use standard Lobster builtins

**Comment by WangWei90** [comment]
Thank you!

I use the latest windows portable TS, and find `script_reference.html` in its doc folder.

Maybe I'm wrong?

![image](https://user-images.githubusercontent.com/20700315/163940767-cae8c654-6985-45ba-b176-276384e090ae.png)

![image](https://user-images.githubusercontent.com/20700315/163941883-58510a5a-e953-4d5a-bd56-e3c59429d075.png)

![image](https://user-images.githubusercontent.com/20700315/163941887-f3446190-0b50-4e4f-b96a-9ab4d21ea1f1.png)

![image](https://user-images.githubusercontent.com/20700315/163942384-f69761c3-e870-44ae-94ad-50a3c205bac0.png)

**Comment by WangWei90** [comment]
Oh. Find this.

![image](https://user-images.githubusercontent.com/20700315/163943029-2ff76146-cfb3-43e3-9751-53941efdc74f.png)

**Comment by aardappel** [comment]
`ts_set_border_color` is indeed not implemented.. you'd have to add a similar function to the existing color functions.

`date_time_string` is in the latest upstream Lobster, but not in the one included in TreeSheets.. that would have to be updated.

**Comment by aardappel** [comment]
Latest Lobster that includes the date functions: https://github.com/aardappel/treesheets/commit/e3c68b0417ea16ecb12c6a9840c0a271c459f870
ts_set_border_color: https://github.com/aardappel/treesheets/commit/d5fcf73354d8ee81fc26d3f30cc2f3b2f0b4865c

**Comment by WangWei90** [comment]
Thank you! I really appreciate your work.

I will try the new version.
