### ISSUE TITLE
Moving cells inside a grid (CTRL+arrow) does update cell text limit rule

### ISSUE THREAD

**Issue by AntonBogun** [aardappel/treesheets#216]
I discovered this by having one cell have very strict text limit (20) and the other the default (80), and then switching the two:
![image](https://user-images.githubusercontent.com/70374466/164541246-78015766-05b2-4391-b98c-6f728a0ed088.png)

**Comment by aardappel** [comment]
Thanks for reporting, fixed here: https://github.com/aardappel/treesheets/commit/f6a8331f83b3f45fa0a1bcc9f9daf63a4305736e
