### ISSUE TITLE
Size of current cell does not get updated after moving with arrow keys

### ISSUE THREAD

**Issue by AntonBogun** [aardappel/treesheets#218]
The display of the size I am referring to is in the lower right corner. It only seems to update properly after clicking on a cell.

**Comment by aardappel** [comment]
The status bar size display is for the cell under the mouse cursor, and does not update when the mouse cursor doesn't move..

**Comment by aardappel** [comment]
That should be fixed here: https://github.com/aardappel/treesheets/commit/3812a6f04ed8f2e9bd7ac3bebf98abe670857d5e

**Comment by AntonBogun** [comment]
Should bar size also update after arrow movement if the mouse has not been moved?
I feel like this is a feature that could be useful

**Comment by aardappel** [comment]
Yes, that's what I just made possible.. try it out.

**Comment by AntonBogun** [comment]
Oh actually I was going to ask what's the most painless way to update TreeSheets?

**Comment by aardappel** [comment]
Download from here (there's builds for all OSes): https://github.com/aardappel/treesheets/actions
