### ISSUE TITLE
Mac continuous build broken

### ISSUE THREAD

**Issue by ctSkennerton** [aardappel/treesheets#223]
I love treesheets so thank you for having it open source and working on it!

I noticed that the github actions are not producing a valid MacOS artifact (despite the green check mark). I saw [here](https://github.com/aardappel/treesheets/actions/runs/2210096135) that the artifact size is only a few kb. The [download from the website](https://strlen.com/treesheets/) still works but not sure how in sync they are.

**Comment by aardappel** [comment]
You're right, it appears to be creating a `.app` bundle with most things missing inside, but the `xcodebuild` command that produces is gives no errors or other indication why that would be so.

Don't have a mac at home anymore, so hard to debug.

As little as 4 days ago it was still working, e.g. this build appears correct: https://github.com/aardappel/treesheets/actions/runs/2209166700

There's a chance this may be temporary?

**Comment by EdMaxPrime** [comment]
I tried building the latest Treesheets source code on OSX 10.15 and the build failed because of a missing file:
```
Build input file cannot be found 'treesheets/lobster/src/vmlog.cpp' (in target 'TreeSheets' from project 'TreeSheets')
```

**Comment by aardappel** [comment]
that file was removed a looong time ago.. CI seems to be able to build the xcode project, are you sure you have latest?

**Comment by aardappel** [comment]
I'll look into it

**Comment by aardappel** [comment]
Ok, turned out the artifact uploader strips permissions and they have no intention of fixing that. Got around it by zipping the file manually first.

Mac builds can now always be found at https://github.com/aardappel/treesheets/releases (and doesn't need a github login anymore)
