### ISSUE TITLE
TreeSheets crashes when my Mac goes to sleep

### ISSUE THREAD

**Issue by samebchase** [aardappel/treesheets#224]
I am on TreeSheets 1.0 on Mac (Big Sur).

Every time the laptop goes to sleep, on wake up, I get a message saying TreeSheets has crashed, and whether I want to restart it.

Let me know if any other information is needed to assist with debugging this.

**Comment by samebchase** [comment]
@aardappel Will try building it with those instructions and file a more detailed bug report. This happens on my work machine which happens to be a Mac. TreeSheets works beautifully on my Linux and OpenBSD machines, otherwise. Thanks once again for all your efforts for creating such a beautifully designed piece of software. 💯

**Comment by aardappel** [comment]
Yes, wxWidgets (upon which TreeSheets is built) has always been implemented less well on max than windows/linux for some reason..
