### ISSUE TITLE
The cursor hovering over the image (and cells?) is broken in the latest TS

### ISSUE THREAD

**Issue by WangWei90** [aardappel/treesheets#228]
Hello, thank you for several latest fixes.

I think the cursor hovering may be broken. 
I would like to toggle off cursor_hovering_function entirely since I have lots of images (and image_centering_when_clicked_function).

Thank you!

![image](https://user-images.githubusercontent.com/20700315/168008894-9b1076c0-2e2d-4e8d-af86-f24991c585a1.png)

![image](https://user-images.githubusercontent.com/20700315/168009681-38e56699-b1af-4eba-85e0-aefcad14dedf.png)

**Comment by aardappel** [comment]
What exactly is not working with image hovering?

Are you telling me from your example image that it renders multiple hover boxes on the image in the wrong location?

It is not doing that for me her locally on images or elsewhere, it seems to work as intended. Can you send me a file that reproduces this problem?

**Comment by WangWei90** [comment]
Thank you for the quick response.

> Are you telling me from your example image that it renders multiple hover boxes on the image in the wrong location?

Yes, your understanding is right.

![image](https://user-images.githubusercontent.com/20700315/168195502-99f63b3e-a132-40b3-bc4e-3f561472ab36.png)

![image](https://user-images.githubusercontent.com/20700315/168195516-25450182-f1c5-4475-a30f-76a180da90cb.png)

The screenshots are from the old test file.


https://drive.google.com/file/d/1m1SMNDA6EudNwh7PJIk6Sl0OU9Px7Nyw/view?usp=sharing

**Comment by WangWei90** [comment]
I am on windows 10 home edition.

I use the portable version of TS.

**Comment by aardappel** [comment]
I cannot reproduce these issues, not even with the file you linked. Any particular actions I have to do to reproduce?

Also on Win 10.

**Comment by WangWei90** [comment]
Well, this is very strange 😅. I don't think there are any other actions related to this.

This is not a big issue for now. Maybe just keep it open and I will add more information if I know.

**Comment by AntonBogun** [comment]
Can confirm this is an issue; reproducible by opening the tutorial.cts, then hovering over the cells in the sub-grid of the "**The basics**" cell, and then scrolling. This results in an incorrect selection highlighting behaviour:
![image](https://user-images.githubusercontent.com/70374466/171059320-67a4e3e8-c782-48f4-8dce-70e5f5836d9a.png)
Mouse cursor hovering over cell "(4)" in the picture, yet there are other highlighting elsewhere in the grid.

**Comment by aardappel** [comment]
I load the tutorial file, hover mouse over (4), scroll (using scrollwheel, or pdn), and see nothing wrong, certainly no multiple selections. On Win10. Anything I am missing to repro this?

**Comment by AntonBogun** [comment]
Here is a video of this happening in a freshly built release of the up-to-date repository.
https://streamable.com/7mqkxt

**Comment by AntonBogun** [comment]
Also an interesting example of what happens with touchpad scroll:
![image](https://user-images.githubusercontent.com/70374466/171191466-dcd17ce7-e500-49e9-bb9f-ebe74c0afdab.png)

**Comment by AntonBogun** [comment]
Windows 10

**Comment by aardappel** [comment]
This is possibly related: https://github.com/aardappel/treesheets/issues/239

I'll get the right version of wxWidgets and see if I can fix things with that.

**Comment by AntonBogun** [comment]
Just built with new changes, the issue is gone. I am using wxWidgets 3.1.6 instead of the latest 3.1.7, but it looks like the changes work.
