### ISSUE TITLE
Deleting last row crashes TreeSheets in latest build

### ISSUE THREAD

**Issue by AntonBogun** [aardappel/treesheets#229]
I downloaded the repository and built TreeSheets. When I launch the created .exe in the TS folder and create a new 10-size grid, if I select and delete 9 rows, and then try to delete a cell in the remaining row TreeSheets crashes.

**Comment by aardappel** [comment]
Pretty sure you're not entirely up to date with the repo, as we had a fix for such a crash recently, and I cannot make it crash with the current version.

If you're entirely up to date, describe exactly mouse actions / key strokes to repro crash.

**Comment by AntonBogun** [comment]
How exactly can I check that the repository I have is up to date?

**Comment by aardappel** [comment]
Does your repo history look like this? Note title of last commit: https://github.com/aardappel/treesheets/commits/master

**Comment by AntonBogun** [comment]
Never mind, it appears that my fork was outdated by one commit, the one which fixed this bug.
