### ISSUE TITLE
Creating a new subgrid using F9 does not retain cell width

### ISSUE THREAD

**Issue by AntonBogun** [aardappel/treesheets#234]

**Comment by aardappel** [comment]
You'll need to be more specific what you mean.

**Comment by AntonBogun** [comment]
The text width of the selected cells will be ignored when pressing F9 and all the columns in the new grid will be 80. 
Instead, the resulting grid should respect the previous widths.

**Comment by aardappel** [comment]
Ah ok, yeah it probably should inherit that.
