### ISSUE TITLE
[BUG] Completely weird display with latest build

### ISSUE THREAD

**Issue by Kochise** [aardappel/treesheets#239]
Using artifact from :

https://github.com/aardappel/treesheets/actions/runs/2436054041

Machine : Windows 10 20H2

Expected :

![capture_20220606_133025_010](https://user-images.githubusercontent.com/23077417/172152924-c5b85545-ba34-4966-9d00-fb5ef0030740.png)

Actual display :

![capture_20220606_133035_012](https://user-images.githubusercontent.com/23077417/172152958-e9ebc0b8-7a58-402f-a6c0-28928a0c3608.png)

**Comment by Kochise** [comment]
Expected :

![capture_20220606_133519_001](https://user-images.githubusercontent.com/23077417/172153414-fb43f21f-357e-472e-a18c-a22f65cb0d97.png)

Actual display :

![capture_20220606_133546_002](https://user-images.githubusercontent.com/23077417/172153454-6bfbe504-1d9a-4417-b2aa-b8e6abaacb8b.png)

**Comment by aardappel** [comment]
Wow, that is wild.. yes, by downloading that same build, I get the same effect here locally.

Looks like wxWidgets has been overhauling how they do their scrolling views in a way that completely breaks TreeSheets.

I bet https://github.com/aardappel/treesheets/issues/228 has the same underlying cause.

I'll get the version of wxWidgets that CI is using and see if I can fix it :)

**Comment by AntonBogun** [comment]
Is the problem in https://github.com/aardappel/treesheets/issues/228 also replicated with wxWidgets 3.1.7?

**Comment by Kochise** [comment]
@aardappel Thank for considering my bug report. Sad that software "evolution" leads to such outcomes. Hope it'll get fixed.

**Comment by Kochise** [comment]
https://github.com/wxWidgets/Phoenix/issues/2150

**Comment by aardappel** [comment]
Thanks, but.. none of those appear to be the problem we're having.

**Comment by aardappel** [comment]
The fixed the bug upstream, so rounded rectangles are now back: https://github.com/aardappel/treesheets/commit/981e0a5640072c311c439119b2c7eadc46ad6efc

See also: https://github.com/wxWidgets/wxWidgets/issues/22493

This does mean that we now do not necessarily support building TreeSheets with older versions as much anymore, should prefer the latest from git always.
