### ISSUE TITLE
Where to download the latest Windows binaries?

### ISSUE THREAD

**Issue by Muns** [aardappel/treesheets#240]
Okay, apologies for being dense, but apart from compiling myself or trying to set up to run an AppImage under Windows - is there an up-to-date binary somewhere, please?

**Comment by aardappel** [comment]
Right here on github (as it says on the TreeSheets main page): https://github.com/aardappel/treesheets/actions (click last green checkmark item, find windows download).

**Comment by Muns** [comment]
Helps if I scroll down! Doh! Thanks Wouter.
