### ISSUE TITLE
Open all links in selection with F5

### ISSUE THREAD

**Issue by AntonBogun** [aardappel/treesheets#241]
If more than one link is desired to be opened, currently there is no way but to select and F5 every single one.

**Comment by aardappel** [comment]
Sounds like a good idea, an probably not too hard to change from the current behavior. Want to have a look at it?

May want to put a limit on the amount of links opened this way? If you had 100 link cells selected that would probably produce a problematic amount of link loading.

**Comment by AntonBogun** [comment]
Yeah I could try to implement it, probably next week.
I'd say 50 links would probably be the max. It'd be nice however if that could be adjustable somehow - is it easy to add new settings to treesheets?

**Comment by aardappel** [comment]
Decently easy, if you just look for an existing setting what variables/code it all touches.

That said, I don't want to clutter the UI with hyper-specialized settings like this. Just make it output in the status bar that you have too many links selected in the unlikely case there's more than 50.

**Comment by t2b3** [comment]
This issue has been resolved with https://github.com/aardappel/treesheets/pull/322. You may close this issue if you agree with this.
