### ISSUE TITLE
Using the function bar interface on win11 is garbled

### ISSUE THREAD

**Issue by xp12047** [aardappel/treesheets#244]
> Please help, the interface is garbled     

![mmexport1659164209264](https://user-images.githubusercontent.com/56335408/181878808-301466d9-44a0-44ba-a254-200fb306e48c.png)
![mmexport1659164204747](https://user-images.githubusercontent.com/56335408/181878810-c23a4d31-8675-4d64-80e0-2a9f62e87774.png)

**Comment by huangfeiqiannian** [comment]
treesheets 官网那个正式版本是旧版本的，中文翻译的编译有问题。
你下载最新版的就没问题了。
单击[此处](https://github.com/aardappel/treesheets/actions)带有绿色复选标记的最新提交，然后选择您的平台。
不过如果作者可以更新一下官网的windows版本就更好了。

=====
The official version of the official website of reesheets is an old version, and there is a problem with the compilation of the Chinese translation.
You can download the latest version.
Click [here]（ https://github.com/aardappel/treesheets/actions ）The latest submission with a green check mark, and then select your platform.
However, it would be better if the author could update the Windows version of the official website.
**Many Chinese people are confused by this error and stop the attempt of usIng treeshees.**

**Comment by xp12047** [comment]
> treesheets 正式版本是英文翻译的官方 版本 ，有 问题[。](https://github.com/aardappel/treesheets/actions)可以更新一下官网的windows版本就更好了。[](https://github.com/aardappel/treesheets/actions)
> 
> ===== reesheets官网的正式版是老版本，中文翻译的编译有问题。 您可以下载最新版本。 点击[这里]（https://github.com/aardappel/treesheets/actions）带有绿色复选标记的最新提交，然后选择您的平台。 不过如果作者能更新官网的windows版本就更好了。 **许多中国人被这个错误弄糊涂了，停止了使用树状结构的尝试。**

谢谢😊

**Comment by aardappel** [comment]
I've updated the builds on https://strlen.com/treesheets/ to latest, and also put the github CI download on top to encourage people to get it from there whenever possible.

**Comment by xp12047** [comment]
> 我已将https://strlen.com/treesheets/上的构建更新为最新版本，并将 github CI 下载放在顶部，以鼓励人们尽可能从那里获取它。

thanks😊
