### ISSUE TITLE
mac app cannot be launched

### ISSUE THREAD

**Issue by core-code** [aardappel/treesheets#246]
after downloading the latest build ( https://strlen.com/treesheets/treesheets_osx.zip ) it cannot be launched because the executable is not marked as executable
<img width="372" alt="Screenshot 2022-08-01 at 23 10 44" src="https://user-images.githubusercontent.com/1261954/182247437-618f6b4f-4b2a-4da6-8b09-4ca426c5c647.png">

after doing
`chmod +x TreeSheets.app/Contents/MacOS/TreeSheets `
it can be launched 

also, the version number is 1.0, just as with previous builds, so it is not distinguishable. i'd recommend increasing the `CFBundleVersion` and `CFBundleShortVersionString` entries in your `Info.plist` file:
<img width="532" alt="Screenshot 2022-08-01 at 23 10 49" src="https://user-images.githubusercontent.com/1261954/182247750-5842e767-c581-4fa1-b442-a286534ac73a.png">

**Comment by aardappel** [comment]
This hopefully fixes the missing executable flag: https://github.com/aardappel/treesheets/commit/8e33c5650a10fe6353301119f1b3dd5deac113f6

The version is a little harder. These are built on CI, and I don't have actual numbered version numbers for TreeSheets other than date. Now it looks like we could set them in CI: https://stackoverflow.com/questions/31467305/xcodebuild-archive-set-version-number-and-build-number but Apple requires a particular format https://developer.apple.com/documentation/bundleresources/information_property_list/cfbundleshortversionstring so the question is how to get a date in the format.

**Comment by aardappel** [comment]
This may work? https://gist.github.com/lifecube/c4041ca1fa65c6e8f53e

**Comment by aardappel** [comment]
ok, added versioning support https://github.com/aardappel/treesheets/commit/8a6d5fa376bbdbe9cf83716ba0f4140274a4a43e and also update the mac binary from CI..

It now has the automatically generated:

```
	<key>CFBundleShortVersionString</key>
	<string>2022.08.02</string>
	<key>CFBundleVersion</key>
	<string>20220802020630</string>
```

**Comment by core-code** [comment]
thanks @aardappel ! using the date in this format for the version numbers makes sense, as it is numerically increasing. i can confirm that this is fixed in newest CI ( https://github.com/aardappel/treesheets/suites/7620408350/artifacts/316432308 ) and stable ( https://strlen.com/treesheets/treesheets_osx.zip ) build.

however both builds still cannot actually be launched, because the `chmod` issue still persists in those.

**Comment by core-code** [comment]
`xcodebuild` definitely should generate a executable with the proper permissions, so i guess the flags get stripped later on, maybe during compression

**Comment by aardappel** [comment]
Ok, turned out the artifact uploader strips permissions and they have no intention of fixing that. Got around it by zipping the file manually first.

Mac builds can now always be found at https://github.com/aardappel/treesheets/releases (and doesn't need a github login anymore)
