### ISSUE TITLE
[Bug] F7 flips cell children in addition to current cell

### ISSUE THREAD

**Issue by shepard8** [aardappel/treesheets#252]
- OS: Arch Linux
- Package: [treesheets-git](https://aur.archlinux.org/packages/treesheets-git)
- Version : Sep 7 2022
- I'm using the i3 window manager (I've seen issue #183 about XMonad, and I'm affected using i3, I don't know if it's related to the bug I'm going to describe).

When trying the tutorial, in the cell explaining how to switch between vertical and horizontal layout, when changing the layout for this particular cell, I noticed the sub-cells are affected by F7 too, which is probably not intended.

The tree screenshots below illustrate what I believe is a bug.
- On the first screenshot, we have the initial situation where one of the sub-cells has a vertical layout and the other a horizontal layout.
- The second screenshot shows the situation after hitting F7 once, notice that the two sub-cells now have both a horizontal layout, whereas I would expect that the sub-cells had kept their layouts (vertical for the former, horizontal for the latter).
- The third screenshot shows what happens after hitting F7 a second time. Notice that both sub-cells have a vertical layout.

![2022-09-07-215623_596x304_scrot](https://user-images.githubusercontent.com/5731430/188967721-f8da6a21-039f-4c56-a9a1-7f177968f175.png)
![2022-09-07-215636_677x193_scrot](https://user-images.githubusercontent.com/5731430/188967727-a10314c8-e0ee-4466-9d3f-807d1d20f7a9.png)
![2022-09-07-215647_639x318_scrot](https://user-images.githubusercontent.com/5731430/188967730-67d15179-e648-4c34-b8a2-7f59953b52be.png)

**Comment by aardappel** [comment]
That is all entirely intentional, as in my experience, when you change layout, you almost always want that for all children too. Having a child that is an exception to the parent is not common, and can usually be achieved by setting that child afterwards.

One could argue it would be nice to have options for both 1 level and multi-level changes, but since there's a lot of operations like this, that would turn into a complicated UI.

**Comment by shepard8** [comment]
Okay, sorry for wasting your time, then :-) And thanks for the explanation/prompt reaction!
