### ISSUE TITLE
Build Artifacts Unavailable without GitHub Account

### ISSUE THREAD

**Issue by wasv** [aardappel/treesheets#254]
I was trying to download treesheets from a computer where I had not yet signed into my GitHub account, and was unable to click the download links on the GitHub actions builds unless I authenticated. It may be worth publishing a release for each successful build so that people without GitHub accounts (or no longer use GitHub) can download your application. New releases can even be part of the [GitHub actions pipeline](https://github.com/ncipollo/release-action).

**Comment by aardappel** [comment]
Hmm.. I am not sure if it makes sense to create a release upon each successful commit.. then again, maybe.. why not?

It ideally shouldn't be on tag, because I have no reason to tag any commit more than any other.

**Comment by wasv** [comment]
They could be marked as a prerelease or nightly build. Its mainly just so the artifacts are downloadable without authenticating and don't get garbage collected after a month (which I think GitHub Actions does).

**Comment by aardappel** [comment]
Ok, there is now a `latest` release that happens on every push: https://github.com/aardappel/treesheets/releases

**Comment by Vaelatern** [comment]
I like the latest build which is of an integer. If it's monotonically increasing, it can be used as a version number for traditional packaging too!

**Comment by aardappel** [comment]
Yup, I changed them to "workflow id" which indeed appears to be increasing: https://github.com/aardappel/treesheets/releases

This does not need commit tagging, just https://github.com/aardappel/treesheets/blob/master/.github/workflows/build.yml#L58
