### ISSUE TITLE
Version development

### ISSUE THREAD

**Issue by nunotexbsd** [aardappel/treesheets#257]
Hello,

I'm updating FreeBSD [port](https://www.freshports.org/deskutils/treesheets/) from 1.0.2 version to latest tag but I have some doubts:

- what will be the version scheme: 1.0.2 -> 3025803779 or 1.0.2 -> 1.0.3 etc?
  This is important to avoid port epoch

- what is the correct way to send CMake var to get version instead of date?
document.h:
```
#ifndef PACKAGE_VERSION
#define PACKAGE_VERSION __DATE__
#endif
```

Thanks

**Comment by aardappel** [comment]
`1.0.2` was a manually applied tag, and it doesn't seem anyone wants to be in charge of maintaining manual versions.

We're now using CI run id as a release tag.. these are increasing numbers, so feel free to use those.

The run id can be passed to CMake in CI script, but would not be available outside of the CI.

**Comment by aardappel** [comment]
Additionally I believe there's ways to query git tag in CMake, but don't ask me how.

**Comment by nunotexbsd** [comment]
Hi @aardappel,

I now understand CI releases tag but it will be very nice that from time to time there will be a release with a better human version like 1.0.x well docomented for those who wanna follow a stable release.

For example, games/exult [ports](https://www.freshports.org/search.php?stype=name&method=prefix&query=exult&num=500&orderby=category&orderbyupdown=asc&search=Search&format=html&branch=head) have an stable release 1.8 and a devel one 1.9.x-TAG based on snapshots, but for most of cases the most important is stable releases.

Cheers

**Comment by nunotexbsd** [comment]
Ok, think I will use gYYMMDD or just YYMMDD for 1.0.2 update.

Thanks
