### ISSUE TITLE
build fails on i386 arch

### ISSUE THREAD

**Issue by nunotexbsd** [aardappel/treesheets#260]
Hello,

FreeBSD treesheets 1.0.2 [port](https://www.freshports.org/deskutils/treesheets/) builds/runs on aarch64, amd64, armv7, i386 and powerpc64.

Latest 3025803779 runs on amd64 but it fails on i386 (other archs not tested):

Any clues?

```
[ 63% 12/19] /usr/bin/c++ -DWXUSINGDLL -D_FILE_OFFSET_BITS=64 -D_THREAD_SAFE -D__WXGTK__ -I/wrkdirs/usr/ports/deskutils/treesheets/work/treesheets-3025803779/lobster/include -I/wrkdirs/usr/ports/deskutils/treesheets/work/treesheets-3025803779/lobster/src -I/wrkdirs/usr/ports/deskutils/treesheets/work/treesheets-3025803779/lobster/external/libtcc -isystem /usr/local/lib/wx/include/gtk3-unicode-3.1 -isystem /usr/local/include/wx-3.1 -O2 -pipe -fstack-protector-strong -fno-strict-aliasing -std=c++17 -pthread -O2 -pipe -fstack-protector-strong -fno-strict-aliasing -MD -MT CMakeFiles/lobster.dir/lobster/src/compiler.cpp.o -MF CMakeFiles/lobster.dir/lobster/src/compiler.cpp.o.d -o CMakeFiles/lobster.dir/lobster/src/compiler.cpp.o -c /wrkdirs/usr/ports/deskutils/treesheets/work/treesheets-3025803779/lobster/src/compiler.cpp
In file included from /wrkdirs/usr/ports/deskutils/treesheets/work/treesheets-3025803779/lobster/src/compiler.cpp:28:
/wrkdirs/usr/ports/deskutils/treesheets/work/treesheets-3025803779/lobster/src/lobster/typecheck.h:1097:17: warning: 16 enumeration values not handled in switch: 'V_MINVMTYPES', 'V_ANY', 'V_VALUEBUF'... [-Wswitch]
        switch (type->t) {
                ^
/wrkdirs/usr/ports/deskutils/treesheets/work/treesheets-3025803779/lobster/src/lobster/typecheck.h:3098:17: warning: 6 enumeration values not handled in switch: 'NF_NONE', 'NF_CONVERTANYTOSTRING', 'NF_PUSHVALUEWIDTH'... [-Wswitch]
        switch (ret.flags) {
                ^
2 warnings generated.
ninja: build stopped: subcommand failed.
```
full [log](https://people.freebsd.org/~eduardo/logs/treesheets/treesheets-1.0.20220909.log)

Thanks,
Nuno Teixeira

**Comment by aardappel** [comment]
TreeSheets (and the included Lobster) hasn't been tried on 32-bit in a long time, I wouldn't be surprised if that is broken, and frankly, I don't see a lot of point in continuing to support 32-bit for a desktop app, given that I don't have a 32-bit machine nor want to spent the time ensuring it works.

That said, this `fatal error: 'i386-gen.c' file not found` should be easy to fix. It is a question of getting the corresponding files from `libtcc` (version 2022-05-26), adding them to `dev/external/libtcc`. If that makes it work, make a PR here and similar one for the Lobster repo.

**Comment by nunotexbsd** [comment]
I've checked `lobster/external/libtcc/readmes/VERSION`, downloaded [tcc-0.9.27.tar.bz2](http://download.savannah.gnu.org/releases/tinycc/tcc-0.9.27.tar.bz2) and added 3 missing i386 files: i386-gen.c, i386-asm.h and i386-link.c and it doesn't build ([log](https://people.freebsd.org/~eduardo/logs/treesheets/treesheets-1.0.20220909_i386_extra_files.log))

I will justify port i386 broken:
```
NOT_FOR_ARCHS=  i386
NOT_FOR_ARCHS_REASON_i386= unsupported platform
```
i386 is still a Tier 1 arch on FreeBSD 12.x version, that's why I was looking for its support.

Thanks very much for your help and it was fun doing this tests!

Cheers

**Comment by aardappel** [comment]
Looks like you used an old version, like I said, it needs to be the one from 2022-05-26: https://repo.or.cz/tinycc.git

Either way, making it unsupported is fine too.

**Comment by nunotexbsd** [comment]
Nice, I will do more tests tomorrow!

**Comment by nunotexbsd** [comment]
https://github.com/aardappel/treesheets/pull/261

**Comment by nunotexbsd** [comment]
Thank you!
