### ISSUE TITLE
Treesheets grabs (almost) all keyboard and mouse input in Xorg environment / gets focus even if window is unfocused

### ISSUE THREAD

**Issue by t2b3** [aardappel/treesheets#262]
Seen with Treesheets on (Arch) Linux
Version (Git): r370.927f542-1
GUI Library: wxwidgets-gtk3 (3.2.1)
Desktop Environment: Xfce 4.16.1 (also reproduced with i3)

![keyboard_focus](https://user-images.githubusercontent.com/3286756/190254167-76da6fb4-37b0-43b8-b86c-a8f0f08c8004.gif)

**Comment by aardappel** [comment]
I've not seen that problem in other OSes / environments, so not sure what is going there..

**Comment by t2b3** [comment]
Hello! Thanks for your fast reply. I dirty-fixed this issue by adding an additional check if the window has focus

`diff --git a/src/myframe.h b/src/myframe.h
index 8facaee..0dbacf6 100755
--- a/src/myframe.h
+++ b/src/myframe.h
@@ -1046,7 +1046,7 @@ struct MyFrame : wxFrame {
     }
 
     void ReFocus() {
-        if (GetCurTab()) GetCurTab()->SetFocus();
+        if (GetCurTab() and wxWindow::HasFocus()) GetCurTab()->SetFocus();^M
     }
 
     void OnCellColor(wxCommandEvent &ce) {`

**Comment by aardappel** [comment]
That sounds like a bug in your windowing system. In other places, setting the focus of a widget does that only inside the TreeSheets window, not globally.

Curious that `wxWindow::HasFocus()` does not require specifying which window...

Either way, we could merge your change if it has no adverse effects to other systems.. care to make a PR?

**Comment by AntonBogun** [comment]
This resolved the issue
