### ISSUE TITLE
Mac OS application not starting

### ISSUE THREAD

**Issue by SamJust** [aardappel/treesheets#264]
System specs
<img width="342" alt="image" src="https://user-images.githubusercontent.com/24614472/190858519-57bcaaeb-1412-4fae-b8b2-55dcf3d2a319.png">
The app is pretty useful, however, it stopped launching. Like, it worked, and since I rarely restart my Mac all was good. However, I had to restart it, due to me getting lazy to plug the charger.
I get this warning and just stop. Even if I launch using terminal I don't get any other info.
<img width="423" alt="image" src="https://user-images.githubusercontent.com/24614472/190858355-0be81060-6d0b-44b0-ac6f-eafc0ea8db0a.png">
> Note: I'm pretty sure this was present during the first launch and worked anyhow

Anyone knows what the issue is? Or at least how to get more info on the error?

**Comment by aardappel** [comment]
What language is your mac set to? A Slavic language I am guessing? We do not have translations for these languages, so that should just default to English and just work.

I wonder why it thinks the locale is `""` as opposed to the usual 2-letter locale code..

**Comment by aardappel** [comment]
Ok, just pushed a change that sets the locale to English if the users locale is not found https://github.com/aardappel/treesheets/commit/af7a5d763d41dce9af37e22c0bc03a5660d89299

Once a release made today shows up here you can test it: https://github.com/aardappel/treesheets/releases

**Comment by SamJust** [comment]
Hi! I do not indeed get the error right now, but the app does not start at all.
<img width="582" alt="image" src="https://user-images.githubusercontent.com/24614472/190917190-9cb0d0cf-8455-466a-b3ae-3cef7d94585a.png">
Are there any logs I cloud possibly provide you to debug the issue further?

**Comment by aardappel** [comment]
you can't really run it from the commandline like that, it won't find its files. Try `open TreeSheets.app` instead.

**Comment by aardappel** [comment]
No idea whats going on there.. and this is with the last release from https://github.com/aardappel/treesheets/releases ?

**Comment by siacali** [comment]
The release listed above opens/works fine for me with a click from the finder. (on 12.6)
