### ISSUE TITLE
Moving windows between monitors with different UI scaling breaks Layout

### ISSUE THREAD

**Issue by honkomonk** [aardappel/treesheets#267]
When the TreeSheet window is moved on a multi-monitor setup to a monitor with a different UI scaling than the monitor it started on, the text size rescales, but all cell borders stick with the old scaling.

![Screenshot 2022-09-20 094857](https://user-images.githubusercontent.com/8714965/191201500-e1cefe7f-d843-4a9a-8e77-3a6956a6451a.png)

**To reproduce:**
OS: Windows 10
TreeSheet release: 3075954433
Monitor Setup:   [1] FullHD Laptop Screen (primary) 125% scaling , [2] 4K Monitor 150% scaling

Open TreeSheets on Screen [1] and drag it onto screen [2].
It recovers after resizing a table, but this has to be done for each table separately.

**Comment by aardappel** [comment]
Ah I can imagine that happening.. it is only getting its scaling settings once at startup, and never queries them again. Maybe if queried them on every redraw that would be an easy fix?

**Comment by jarrad2000** [comment]
I have a similar issue but in my case the relations between menu and content is also messed up.

**TreeSheets on the low resolution display (huge menu on top)**
![image](https://user-images.githubusercontent.com/1764091/195579258-c4010373-55ba-4b1f-8ebb-73f9230d5a83.png)

**TreeSheets on the high resolution display (messed up content and tiny status bar on the bottom)**
![image](https://user-images.githubusercontent.com/1764091/195579406-e0ca06c1-117b-4a2b-a6f7-4df2012408c5.png)

**System**
OS: Windows 10 Enterprise 21H2
TreeSheets: Version Sep 26 2022
High res display: 3840x2160 @250% scale (it's a 15" laptop display with UHD)
Low res display: 1920x1080 @100% scale (it's a 27" external display with HD)

**Comment by t2b3** [comment]
This has been fixed by various commits using HiDPI support from the underlying wxWidgets platform.
