### ISSUE TITLE
Why is refocus disabled?

### ISSUE THREAD

**Issue by char101** [aardappel/treesheets#27]
Hi,

I wonder why is `ReFocus()` commented in

https://github.com/aardappel/treesheets/blob/master/src/myframe.h#L838

this causes the active cell to lose selection after alt-tab-ing to another window and back.

**Comment by aardappel** [comment]
It was disabled in https://github.com/aardappel/treesheets/commit/2cca4874c993c5f20ea23a5ec18924a393def266
From what I remember, it was causing some SetFocus related debug warnings on Windows.

**Comment by char101** [comment]
But this causes inconsistency when refocusing the window. The cursor is blinking in the cell but typing does not produce anything. So I have to focus the cell manually.

When copy pasting information from another window, this will cause extra effort from switching from the keyboard to the mouse and back.

**Comment by aardappel** [comment]
Sorry, let this one slip. I've re-enabled it.
