### ISSUE TITLE
ESC while typing removes last word

### ISSUE THREAD

**Issue by AntonBogun** [aardappel/treesheets#270]
When trying to stop typing in a cell, pressing ESC will effectively have the same effect as CTRL+Z, in that it undoes the last typed word.
I've found that if I want to not do that the easiest way is to press Tab followed by Shift+Tab or up arrow followed by down arrow, but that doesn't seem like the intended behaviour.
Additionally, if this is fixed it would make sense to look at [this](https://github.com/aardappel/treesheets/issues/221) as well.

**Comment by aardappel** [comment]
This is not a bug, that is intended behavior. Same happens in spreadsheets, from which the UI was derived.
