### ISSUE TITLE
Typo in message when saving a sheet

### ISSUE THREAD

**Issue by Abakus2k** [aardappel/treesheets#273]
When saving a sheet, in the bottom bar a text is displayed: "Saved [...] succesfully (in n miliseconds)."
It should be "successfully"
![image](https://user-images.githubusercontent.com/51076490/195068296-1c935c3f-dec5-41a0-b772-2cd365199783.png)
Its a minor typo but really annoying on a daily base.

**Comment by aardappel** [comment]
Fixed, thanks.
