### ISSUE TITLE
Multi line paste is not working in macOS Ventura 13.0.1 (22A400)

### ISSUE THREAD

**Issue by moebiuscurve** [aardappel/treesheets#302]
Multi line paste (after multi line copy from another source format like pdf or sublime text editor) is not working in macOS Ventura 13.0.1 (22A400)
![treesheetsMultilineText](https://user-images.githubusercontent.com/282239/206852937-7e4a279a-d19b-4eff-9bec-b6db4b26619f.png)

**Comment by moebiuscurve** [comment]
It should paste in multiple lines.

**Comment by moebiuscurve** [comment]
It looks to be something specific with the latest version of macOS. I tested an old version of treesheets, which was earlier working, and it has the same issue now. It seems this bug needs to be identified and raised with the macOS team.

**Comment by moebiuscurve** [comment]
But if you could fix this somehow, I would really be grateful. I copy multiple lines from pdfs while making notes on treesheets. And this breakage will really affect me adversely.

**Comment by moebiuscurve** [comment]
Even image pasting is no longer working.

**Comment by aardappel** [comment]
Fixed here: https://github.com/aardappel/treesheets/commit/9ef911aa6678660924df4c4cdd419d215f1e42e9

**Comment by aardappel** [comment]
I think MacOS at some point changed the default line separating character from `\r` to `\n` and we never noticed.

**Comment by moebiuscurve** [comment]
Thanks a lot, :-). You are just awesome. You have no idea how much I am dependent on this app you have created.
