### ISSUE TITLE
Have you considered adding support for vim mode

### ISSUE THREAD

**Issue by xp12047** [aardappel/treesheets#313]
It is a bit cumbersome to press the up, down, left, and right keys on the keyboard, and you need to leave the letter key area.  Can you add h, j, k, l in vim mode to it.  Thank you if there is more of course more.

**Comment by aardappel** [comment]
the problem is that `hjkl` would currently start typing in the cell with those letters, so this vim mode would need special UI to change mode such that those letters can be typed normally.. that is a bit too much special case UI/code for the purpose.

**Comment by xp12047** [comment]
> 问题是`hjkl`当前会开始在单元格中输入这些字母，因此此 vim 模式需要特殊的 UI 来更改模式，以便可以正常输入这些字母..对于这个目的来说，特殊情况下的 UI/代码有点太多了.

All right

**Comment by xp12047** [comment]
> 问题是`hjkl`当前会开始在单元格中输入这些字母，因此此 vim 模式需要特殊的 UI 来更改模式，以便可以正常输入这些字母..对于这个目的来说，特殊情况下的 UI/代码有点太多了.

Wow, I found that it works well with this software.
