### ISSUE TITLE
Tags to indicate "good to use" versions

### ISSUE THREAD

**Issue by infinity0** [aardappel/treesheets#32]
I'm packaging this for Debian. Would you mind tagging commits from time to time, so that I can identify versions that are "good to release" to general users? A short version string would be nice too, otherwise I will have to call it something like `treesheets_20150519+git69990a2f`.

**Comment by gwvo** [comment]
Hmm.. will have to see how we do this, since I have no QA process, unstable channels or any of that stuff, so the best version for users is always the latest, as far as I am concerned.

I could tag versions that I feel better about than others, but probably that only means that Debian users will be behind on bug fixes most of the time.

Can you use the date as version? That's what the app itself does (in the about menu). I don't do traditional versions as they tend to become meaningless.

**Comment by infinity0** [comment]
I can use the date of the last git commit as the version, but this is not the same as `__DATE__`, which is the *build* time.

You could do something like `CXXFLAGS += -DVERSION=$$(git show -s --format='%ci .%h' | cut -b1-4,6-7,9-10,27-34)` in the Makefile which results in something like `20150519.69990a2f`. On top of that, it would be good to reflect this in the filename of the tarballs you publish, instead of it being buried in the About dialog box.

(Generally, we're trying to discourage people from using `__DATE__` and build-time things, see https://wiki.debian.org/ReproducibleBuilds/TimestampsProposal for background.)

**Comment by aardappel** [comment]
I agree they're not quite the same, but the date of the commit is really the canonical version. I use __DATE__ to keep things simple.. same for the tarball naming :)

**Comment by infinity0** [comment]
Yeah sure, it just makes it a bit awkward to figure out which git commit a particular tarball corresponds to. But I suppose as long as you're not officially releasing source tarballs, I can just fake the "upstream tarball" for Debian and do a "git archive" at a particular commit.

**Comment by aardappel** [comment]
What do you need my tarballs for, though? I generate binaries pretty infrequently. The contents of the tarball is simply the `TS` folder in the repo (with the binary after a build).

**Comment by infinity0** [comment]
I need tarballs of the *source* package, it's just how Debian packaging works. Most FOSS projects have these, it's sort of a convention, and the Debian project generally believes this is a good thing to do, so they haven't tried to update the standard to remove this requirement.

For projects released directly from VCS that make no tarball releases, there *are* some Debian tools that essentially generate a "pretend" upstream tarball, so it's not a massive problem. But let me know if you do decide to release "official" source tarballs one day, and I can then do it the "proper recommended way" and/or give you some info on "best practises" with that.

**Comment by aardappel** [comment]
Ahh ok.. yeah people that want source typically are ok with using github.

**Comment by Vaelatern** [comment]
I'm regularly tagging commits after a flurry of activity and then a period of no action. I assume that if people using HEAD don't notice any problem in a couple weeks, it's safe to tag.

These tags are then pushed to Void Linux's repos, though they are available to other distributions.

I suspect this issue may be closable.

**Comment by aardappel** [comment]
@Vaelatern that could even be an automated thing: see commits with longest gap between them :)
