### ISSUE TITLE
Cannot set locale to language

### ISSUE THREAD

**Issue by aryehof** [aardappel/treesheets#324]
Every time the application is started I get a Treesheets Warning dialog stating ...

Cannot set locale to language "English (Cyprus)".

(Release 3809129847 - 31Dec2022, MacBook Pro M1)

**Comment by aardappel** [comment]
Does it still run afterwards?

Not sure why it is doing that, as that error isn't coming from my code. It simply does:

```
        auto lang = wxLocale::GetSystemLanguage();
        if (lang == wxLANGUAGE_UNKNOWN || !wxLocale::IsAvailable(lang)) {
            lang = wxLANGUAGE_ENGLISH;
        }
        locale.Init(lang);
```

That seems to work even on machine with broken locale setups.

**Comment by aryehof** [comment]
Yes it does still run afterwards. It's an annoyance, but sounds like a wx issue.
