### ISSUE TITLE
Some images cannot be added

### ISSUE THREAD

**Issue by mwgamera** [aardappel/treesheets#335]
When trying to add a new image to a sheet, it sometimes inserts one of the previously loaded images instead of the new one. There is no error message nor warning; just a different image than selected appears in the cell.

To reproduce, try adding the two images attached to two cells in a sheet. One shall load without any problems, but it shall be impossible to add the second one.
![V_5146_1](https://user-images.githubusercontent.com/903892/215956911-e585acd7-7c05-492f-97f1-5145f62a5fc3.gif) ![CI_5bff_1](https://user-images.githubusercontent.com/903892/215956909-3f997013-5eca-4edd-8e70-f93c35aa4388.gif)
I was able to reproduce it using the linux build of the 3989467383 release.

Apparently TreeSheets de-duplicates images using a ‘checksum’ without ever verifying whether they are actually the same. This wouldn't be a problem if ‘checksum’ were a sufficiently long collision-resistant hash, but it is not a reasonable hash or a checksum at all.
It's not only trivial to find collisions intentionally, but it is also possible to stumble into them by accident like I did. It is particularly likely in case of bi-level (black and white) images or images with low number of colors in general. There are only 16 possible values of ‘checksum’ for bi-level images of particular size.

**Comment by aardappel** [comment]
That is indeed a terrible way to checksum for b&w pixels :) I replaced it with a 64-bit hash function, that should do a bit better..

**Comment by aardappel** [comment]
https://github.com/aardappel/treesheets/commit/44206849d03c8983e41d2aeca70a06e04365d88d

**Comment by mwgamera** [comment]
FNV isn't what I would call a ‘sufficiently long collision-resistant hash’, but it is probably good enough.
It certainly fixes my issue with b&w images. Thanks!

**Comment by aardappel** [comment]
it's what I had handy.. it should be a huge improvement over what was there :)
