### ISSUE TITLE
Crash when extending selection with mouse after deleting a child grid

### ISSUE THREAD

**Issue by jn64** [aardappel/treesheets#349]
treesheets version: [4338874921](https://github.com/aardappel/treesheets/releases/tag/4338874921) ([my build here](https://download.copr.fedorainfracloud.org/results/jn64/treesheets/fedora-37-x86_64/05597553-treesheets/))
OS: Fedora 37

Steps to reproduce:

1. Insert a child grid (press `Insert`)
2. Select the new child grid with mouse (must explicitly click on it, even though it already appears selected)
3. Delete the child grid (press `Delete`)
4. Press and hold `Shift`, and click on another cell — treesheets crashes

Notes:

- If you skip step 2, there is no crash
- Using keyboard instead of mouse to extend the selection also doesn't crash

---

I attached an example doc:

[crash-selection-example.zip](https://github.com/aardappel/treesheets/files/10907196/crash-selection-example.zip)

![crash-selection-example](https://user-images.githubusercontent.com/23169302/223365963-ba2cbebd-1a40-48ce-9747-26878c83766d.png)

**Comment by aardappel** [comment]
Thanks, will look into it!

**Comment by aardappel** [comment]
Fixed here: https://github.com/aardappel/treesheets/commit/6672b90aa6310f2a02d9527f500645dd525a8fe3
