### ISSUE TITLE
Shift+F10 brings up context menu instead of folding on Linux

### ISSUE THREAD

**Issue by despens** [aardappel/treesheets#36]
Version: TreeSheets Jun 16 2015

DE: Gnome Shell 3.10

Pressing `Shift+F10` in a cell brings up the cell's context menu, instead of folding the cell.

**Comment by aardappel** [comment]
The menus show this is CTRL+F10.. I guess it is shown wrong in the tutorial, will fix.

**Comment by despens** [comment]
Thanks a mil, `Ctrl+F10` works, life improved!
