### ISSUE TITLE
CTS file saved on Windows wont open on Linux

### ISSUE THREAD

**Issue by codingRubbish** [aardappel/treesheets#368]
Hello,

As the title suggests I have had issues opening a .cts file saved on Windows.

The file originally came from my Linux machine (MX Linux 21; fluxbox edition). I moved it to a Windows computer and it opened no issues. I then moved it back to my Linux machine and Treesheets displays this error/message: File of newer version.

I have the latest version of Treesheets on both machines.

I have got around this by exporting the Windows file to XML on WIndows and importing it into Treesheets on my Linux machine but this is far from ideal.

Thanks for reading.

**Comment by aardappel** [comment]
If you get that error then that simply means you do not have the latest version on Linux? Try with latest from https://github.com/aardappel/treesheets/releases

**Comment by codingRubbish** [comment]
My apologies when I said I was running the latest on my Linux machine. I mistyped on the terminal and was actually running the version installed from the repositories.

Unfortunately neither version Linux version works on my Linux machine without me having to manually install multiple shared libraries. One of which is `libjpeg.so.8` which is not available on Debain (the based on MX Linux) which uses `libjpeg62-turbo`.

Looks like I'm stuck with the XML workaround until the repositories are updated.

Apologies for wasting your time, thanks for taking the time to answer my issue.

**Comment by aardappel** [comment]
I cannot fix Linux's broken package management sadly ;)
