### ISSUE TITLE
menu item 'Help ➝ View tutorial web page...' misbehaviour

### ISSUE THREAD

**Issue by dahn-d** [aardappel/treesheets#38]
http://www.usr.com/share/treesheets/docs/tutorial.html
this is the page that firefox tries to load when i click button mentioned in title :)
EDIT^2: and my version is Sep 23, ok now im on Oct 26 and the problem remains

**Comment by aardappel** [comment]
On what OS?
It tries to load the file `docs/tutorial.html`, not sure how that can get translated to a `usr.com` url..

**Comment by dahn-d** [comment]
Arch Linux

**Comment by aardappel** [comment]
It appears the function I use, `wxLaunchDefaultBrowser`, is very broken on Linux. On Ubuntu it tries to launch `gvfs-open file://./docs/tutorial.html` even though `gvfs-open` doesn't understand `file://`. Still, not sure where it could possibly get that url from.

**Comment by aardappel** [comment]
What is the `pwd` from where you invoke treesheets, and what is the full command-line how you invoke it?

**Comment by dahn-d** [comment]
i've installed treesheets from arch linux user repository so its just in ``/usr/bin/treesheets`` but apparantly ``docs/`` is not bothered to be copied to ``/usr/share/treesheets/`` during installation process. the problem solved by adding that ``cp`` command to installation mechanism my os provides and it works like charm. it was not code problem, sorry. thanks for question about working directory; i had no idea that scripted installation is different from those u provided in readme.

**Comment by aardappel** [comment]
can you report this problem to the arch linux maintainers?

**Comment by dahn-d** [comment]
sure, i've reported the problem to package maintainer already.
