### ISSUE TITLE
input line (formula bar)

### ISSUE THREAD

**Issue by edmundlaugasson** [aardappel/treesheets#40]
Would propose to add input line where would be possible to see whether the number is entered directly or is it result of formula. Just like at spreadsheet program - it would be very helpful.

**Comment by aardappel** [comment]
There currently aren't any cells that are the result of a (hidden) formula, so that wouldn't improve anything.

Also I think it is generally easier to type text at its destination, since it is easier to see its context that way.

**Comment by edmundlaugasson** [comment]
Well, there are calculations allowed and the question appeared - was the number written directly or is it a result of calculation.

**Comment by aardappel** [comment]
Sure.. but the calculated number is not hiding a formula, the formula is elsewhere.

**Comment by edmundlaugasson** [comment]
I see. The cell coloring makes it understandable.
