### ISSUE TITLE
Serious bug on Linux 

### ISSUE THREAD

**Issue by rotacoder63** [aardappel/treesheets#439]
I'm using Xubuntu 23.04 and have install Treesheets 1.02 from the ubuntu repository. The issue is that when Treesheets is open, no other applications can get focus, not even when I switch to another workspace. Essentially, Treesheets takes over the entire desktop.

**Comment by aardappel** [comment]
Please do not get it from the repository, that is likely many years old. See if the problem still exists with recent releases: https://github.com/aardappel/treesheets/releases

**Comment by aardappel** [comment]
You are likely on an older version of your distro?

**Comment by rotacoder63** [comment]
No, it was only released a couple of months ago, maybe not quite as up-to-date as Fedora though. I downloaded the Windows version which runs ok on the Wine emulator, so I'll use that for now.

**Comment by jn64** [comment]
Ubuntu 23.04 ships libtiff6 (4.5.x). The GitHub builds are on Ubuntu 22.04 libtiff5 (4.3.x)

**Comment by rotacoder63** [comment]
Ok, thanks.
