### ISSUE TITLE
Debian 12: error while loading shared libraries: libjpeg.so.8

### ISSUE THREAD

**Issue by cefer60** [aardappel/treesheets#501]
Clicking over treesheets file on my debian 12 nothing happen, so i open a terminal window and execute from command line:
./treesheets
and a error message appear:
./treesheets: error while loading shared libraries: libjpeg.so.8: cannot open shared object file: No such file or directory
But searching for this library, several libjpeg appear, Wich i do install? And others packages needed?

**Comment by aardappel** [comment]
There have been several issues discussing this already, please see there:
https://github.com/aardappel/treesheets/issues/292
https://github.com/aardappel/treesheets/issues/198
