### ISSUE TITLE
html export, white text on white background

### ISSUE THREAD

**Issue by underwoodblog** [aardappel/treesheets#502]
html export outputs not every cell with textcolor. when the parent cell has different collor scheme, this can lead to white text on white background.

![grafik](https://github.com/aardappel/treesheets/assets/25827173/b2faad0b-4d1a-4693-9c07-dd341e4a0d99)

```
<td style="">
  <table style="border-width: 2pt; font-size: 13pt;">
  <tr>
  <td style="font-family: monospace;background-color: #000000;color: #FFFFFF;">2023-09-06
    <table style="border-width: 2pt; font-size: 12pt;">
    <tr>
    <td style="background-color: #FFFFFF;">06.09.2023 11:15:00
    </td>

```

**Comment by t2b3** [comment]
See the PR for a fix
![image](https://github.com/aardappel/treesheets/assets/3286756/2a0a068d-3869-4749-a69d-a22cb9e3915c)

**Comment by aardappel** [comment]
Yup that looks perfect :)
