### ISSUE TITLE
idea: cell(s) split and join

### ISSUE THREAD

**Issue by edmundlaugasson** [aardappel/treesheets#51]
For more flexible editing the cell(s) split and join would be appreciated.

**Comment by aardappel** [comment]
For joining cells, "Copy as continuous text" is useful. Splitting is pretty easy with "Cut". I agree it is potentially useful to have more direct operations, especially for split.

**Comment by edmundlaugasson** [comment]
I have to admit that for me the "Copy as continuous text" does nothing - possibly I do not know how to use it properly. I entered text into first cell, selected two cells and used that command. Also tried enter text into two cells, selected them and used the command.
"Cut" could be used, that is true.

**Comment by aardappel** [comment]
After you use "Copy as continuous text" you have to Paste the result somewhere

**Comment by edmundlaugasson** [comment]
OK, clear - it works.
