### ISSUE TITLE
master branch history rewritten?

### ISSUE THREAD

**Issue by jn64** [aardappel/treesheets#536]
2 commits disappeared from master branch

- https://github.com/aardappel/treesheets/commit/3b45aa9c809ef6486206664b8e6717559c48dd68
- https://github.com/aardappel/treesheets/commit/b728fe6dd034fe80cc46b8ebaaa20b30f018c9d9

Please don't rewrite published history, use `git revert` even if it looks ugly...

**Comment by aardappel** [comment]
@t2b3 I see a force push recently.. better not to do those unless absolutely needed

**Comment by t2b3** [comment]
> @t2b3 I see a force push recently.. better not to do those unless absolutely needed

Ok thanks for your feedback. It should not happen again.

**Comment by jn64** [comment]
Thanks for your understanding
