### ISSUE TITLE
flatpak release isn't latest

### ISSUE THREAD

**Issue by caius-martinus** [aardappel/treesheets#547]
Hi,
Just a quick notice : the current [Flathub](https://flathub.org/apps/com.strlen.TreeSheets) release mention `Changes in version 6364166541` which is 20 days ago.

**Comment by t2b3** [comment]
> Hi,
> 
> Just a quick notice : the current [Flathub](https://flathub.org/apps/com.strlen.TreeSheets) release mention `Changes in version 6364166541` which is 20 days ago.
> 
> 
> 
> 

Hi
Thanks for reporting this. I will update version mentioned in the Flatpak description. I did not update the version history but the binaries provided correspond to the latest commit.
Kind regards
Tobias
