### ISSUE TITLE
Missing shortcut for inserting a grid in a cell

### ISSUE THREAD

**Issue by amoulart** [aardappel/treesheets#551]
Hello,

I'm using TreeSheets Oct 23 2023 on windows 10 Home 10.0.19045 with a French keyboard.
I've just installed the program and it is operating in French language.
When I try to insert a new grid in a cell the "inser" (INS in english) key is not doing anything. I'm forced to use the Icon in the toolbar or the command in the right-click popup menu.
I've tried also with the visual keyboard with no success.
I can see that in an other program (Libreoffice for example) that this key is operating correctly.
I can see also that no shortcut is displayed in the right-click popup menu:
![image](https://github.com/aardappel/treesheets/assets/6957856/0a3d12b0-2c7c-4052-a2c1-5076285a377b)
I don't understand how to setup a shortcut value for that function through the dedicated menu>Options>Modify shortcuts

Thank for you help,
I've just tried your app and gave me very good results in a very short time!

**Comment by georgeraraujo** [comment]
I took a look at the translation file for French and the translation for "Insert New Grid" really is missing the "INS" keyboard shortcut. I added it in case you want a quick fix:

1. Download [fr_FR.zip](https://github.com/aardappel/treesheets/files/13232792/fr_FR.zip) and put it in your `%LOCALAPPDATA%\Programs\TreeSheets\translations\fr_FR` folder.
2. Copy `ts.mo` and `ts.po` to a backup folder of your choice.
3. Uncompress the `fr_FR.zip` file you downloaded, and confirm that you want to overwrite `ts.mo` and `ts.po` (which you made backup copies of in the previous step).
4. Start TreeSheets. The menu entry should now include the INS keyboard shortcut.

I noticed there are several untranslated strings in the French translation. Consider translating them and submitting a pull request.

**Comment by amoulart** [comment]
Thank you Georger, it works like a charm. 
I can do the translation work but I'm not used to the tools. 
I see I can edit the po file with notepad++ can you confirm I should use the compile.bat/sh files to generate the mo file?

**Comment by georgeraraujo** [comment]
> Thank you Georger, it works like a charm. I can do the translation work but I'm not used to the tools. I see I can edit the po file with notepad++ can you confirm I should use the compile.bat/sh files to generate the mo file?

While you definitely can edit `ts.mo` with Notepad++ and then use `compile.bat` to generate `ts.mo`, that would require you to obtain the GNU gettext utilities, put them exactly in the folder where `compile.bat` expects them to be, and finally invoke `compile.bat` by hand. Since you're using Windows, I recommend that you use [Poedit](https://poedit.net/) instead, which will allow you to edit and compile with a single tool. I use the free version for the Brazilian Portuguese translation, and haven't felt the need to upgrade to the paid Pro version.

**Comment by amoulart** [comment]
Ok I've started the work but there is a lot to do and sometimes I'm not sure about what I'm modifying so it will take some work for verification on my side. I'll push it when I assume it is reliable.

**Comment by georgeraraujo** [comment]
> It looks like not all HMI entries are appearing in the translation file.

It looks like `TS\translations\fr_FR\ts.po` is out of date with `TS\translations\ts.pot`. In Poedit, Click **Catalogue** > **Mettre à jour depuis un fichier POT...**, and choose `ts.pot` in the `translations` folder. It will merge the latest strings from `ts.pot` into `ts.po`, and make them available for you to translate.
