### ISSUE TITLE
[Share] zh-CN language for TreeSheets Nov 13 2023

### ISSUE THREAD

**Issue by xkonglong** [aardappel/treesheets#557]
[zh_CN.zip](https://github.com/aardappel/treesheets/files/13446534/zh_CN.zip)

 Fixed untranslated content .

**Comment by xkonglong** [comment]
![image](https://github.com/aardappel/treesheets/assets/9131496/2384c3d3-a5c6-4daf-8d6d-2cfa51f1f959)

**Comment by aardappel** [comment]
can you make a PR?

**Comment by t2b3** [comment]
I hope I was not too hasty but I took the files and committed them to the repository.

**Comment by t2b3** [comment]
@xkonglong Thank you for your translation work :+1:
