### ISSUE TITLE
Shortcuts for switching between documents/tabs not working

### ISSUE THREAD

**Issue by tomatic** [aardappel/treesheets#558]
I'm using TreeSheets Nov 13 2023 on Kubuntu 22.10 and I think I've found a bug.

The menu items _View > Switch to next file/tab_ and _View > Switch to previous file/tab_ work when used via the menu, but keyboard shortcuts don't work (do nothing). The _switch to previous_ menu item actually already seems to have the shortcut CTRL+SHIFT+TAB assigned to it by default, but it doesn't work. I assigned CTRL+TAB to the _switch to next_ item but that doesn't work either. The bindings also do not show next to the menu items.

To test, I assigned the shortcut CTRL+SHIFT+F12 to _Toggle Zen Mode_. That works as expected and the shortcut shows next to the menu item (after a restart).

**Comment by tomatic** [comment]
I just tested some more and it appears that pressing Ctrl+Tab or Ctrl+Shift+Tab makes navigating the sheet with the arrow keys temporarily impossible, i. e. pressing any arrow key does nothing. Only after clicking somewhere in the sheet the arrow keys work again.

**Comment by t2b3** [comment]
Please see
https://github.com/aardappel/treesheets/blob/7471837f2d2a71de51bfeada16b5a52b13e2ce5e/src/document.h#L943C16-L957C34

As long as the underlying framework (wxWidgets) keeps translating Ctrl+A - Ctrl+Z to the corresponding ASCII control character and further to its modern equivalent, there is not much we can do about it, I guess?
