### ISSUE TITLE
Verification in flathub

### ISSUE THREAD

**Issue by NameLessGO** [aardappel/treesheets#561]
Hi there, I've been contacting flatpak projects to request validation in their package so that people would have more faith in the app and in flathub.

The app is recognized as an official instalation method

<img width="324" alt="image" src="https://github.com/aardappel/treesheets/assets/66227691/de1a0238-956c-4398-8459-8c49d9f9b804">

----

> A verified app is an app that is published on Flathub by its original developer or a third party approved by the developer. Flathub has verified the developer's identity using the app id and the developer's website or profile on a source code hosting site.

Verification docs: https://docs.flathub.org/docs/for-app-authors/verification

Flatpak source code: https://github.com/flathub/com.strlen.TreeSheets

Flatpack: https://flathub.org/apps/com.strlen.TreeSheets

**Comment by t2b3** [comment]
Thanks for your effort and the provided links.
Nevertheless, I think we will not do this. I would like to keep the source distribution completely independent from the Flatpak package distribution and the verification requests that the original author must place a file on his website. As stated, I do not want to make things dependent on each other that can be maintained separately.
