### ISSUE TITLE
Install code typo in x11 install.md?

### ISSUE THREAD

**Issue by noyannus** [aardappel/treesheets#564]
Building instructions for [wxWidgets](https://github.com/wxWidgets/wxWidgets) may contain a typo.

`--disabled-shared ` throws an error, 
`--disable-shared`  does not.

Seen running `./configure --with-x11 --enable-unicode --disable-shared` on SUSE Tumbleweed.

**Comment by t2b3** [comment]
Thank you for reporting the typo. It should be fixed by now.
