### ISSUE TITLE
Menus disabled in version 7314842728

### ISSUE THREAD

**Issue by noyannus** [aardappel/treesheets#576]
The menus are disabled like this:

![Screenshot_20231228_130017](https://github.com/aardappel/treesheets/assets/6339921/97d4b4a2-5c3d-4e52-9f1c-2e74f1d8eb8c)

It happens with version 7314842728, on unpacked `linux_treesheets_clang++-14.zip` and `linux_treesheets_g++-12.zip`.

Seen on 

Operating System: openSUSE Tumbleweed 20231225
KDE Plasma Version: 5.27.10
KDE Frameworks Version: 5.113.0
Qt Version: 5.15.11
Kernel Version: 6.6.6-1-default (64-bit)
Graphics Platform: X11

**Comment by aardappel** [comment]
This look like a window manager problem, not related to TreeSheets.

I'd recommend trying a window manager that does not stick all menus of an app into some special drop down.

**Comment by noyannus** [comment]
Thanks for the advice! I'll try that as last resort, such a big change.

The Flatpak version does not have that menu issue, but freezes Tumbleweed (only cursor can be moved, fan revs up, must be rebooted from root session).

Trying VMs now. This application is too good to not use. :-)

**Comment by aardappel** [comment]
So? what was your final solution?

**Comment by noyannus** [comment]
Try to integrate a Kubuntu VM as seamlessly as possible. The VM version, too, has a flaw that I' address in a separate issue to keep things tidy.
