### ISSUE TITLE
CSV export broken

### ISSUE THREAD

**Issue by noyannus** [aardappel/treesheets#577]
On exporting as .csv, nothing happens. No file appears in the exported-to directory.

To reproduce: try exporting the tutorial as .csv.

Seen on a virtualbox VM running

--
Kubuntu 23.10
KDE Plasma 5.27.8
KDE Frameworks 5.110.0
Kernel 6.5.0-14-generic (64bit)
X11

with TreeSheets
Dec 18 2023
wxwidgets 3.3.0

--
virtualbox VM running 
Linux Mint 21.2 Cinnamon
Cinnamon 5.8.4
Kernel 5.15.0.-91-generic

with TreeSheets
1.0.2
Here, on one time only, a file was exported that contained `1592\00`. 

--
virtualbox VM running 
openSUSE Tumbleweed 64bit
GNOME
45.2
Wayland
Kernel 6.6.7-1-default
with TreeSheets
Dec 18 2023
wxwidgets 3.3.0

--
on real machine running
Operating System: openSUSE Tumbleweed 20231225
KDE Plasma Version: 5.27.10
KDE Frameworks Version: 5.113.0
Qt Version: 5.15.11
Kernel Version: 6.6.6-1-default (64-bit)
Graphics Platform: X11

-- 

So it's not the OS, the desktop, the window manger, nor the kernel.

Edit: this is the case with nested cells in the layout, not with a not nested layout.

**Comment by aardappel** [comment]
Check what it says in the status bar.

**Comment by noyannus** [comment]
Ahhh! Lightbulb moment. Thank you.

That leads me to think more about it. A suggestion: the explanations for the export format in the status bar are only visible when the cursor is in the export submenu. That is easy to miss (at least for me :-) ) when going too fast through the menus.

Would it be possible to keep the explanation visible until the file save dialog closes? Or have it repeated on the dialog footer (space is enough there)? Or provide some feedback, say, as an error dialog, or by disabling the csv export item when the layout is not flat? 


Closing as this is obviously not a serious issue.

Have a good 2024!
