### ISSUE TITLE
add a .desktop file for gnu/linux users

### ISSUE THREAD

**Issue by infinity0** [aardappel/treesheets#60]
A Debian user at https://bugs.debian.org/818965 would like there to be a `.desktop` file for easier usage. Here is an example:

~~~~
$ cat /usr/share/applications/freeplane.desktop 
[Desktop Entry]
Version=1.0
Name=Freeplane
Exec=/usr/bin/freeplane %F
Terminal=false
Icon=freeplane
Type=Application
MimeType=application/x-freeplane;
Categories=Office;
GenericName=Freeplane
Comment=A free tool to structure and organise your information with mind mapping
Keywords=Mindmaps; Knowledge management; Organize information; Brainstorming; ...;
~~~~

**Comment by dahn-d** [comment]
[This](https://github.com/aardappel/treesheets/blob/master/TS/treesheets.desktop)?

**Comment by aardappel** [comment]
If you have any improvements to the existing file, feel free to make a PR, or let me know.

**Comment by infinity0** [comment]
Thanks, I missed that since I last checked. I just opened #61 to add a few more fields.
