### ISSUE TITLE
F7 not working to toggle text placement to above or beside grids

### ISSUE THREAD

**Issue by uteweigel** [aardappel/treesheets#602]
This feature is not working, per the tutorial. "You can toggle text placement to above the grid (vertical layout, like much of this document) or besides (horizontal layout) by pressing F7 on any selection:".

**Comment by t2b3** [comment]
You seem to have an outdated tutorial file.
![image](https://github.com/aardappel/treesheets/assets/3286756/8298bced-a3fc-4142-9312-f005d9b4f76b)

**Comment by uteweigel** [comment]
Excellent - ty so much!!!!

**Comment by t2b3** [comment]
> Excellent - ty so much!!!!

You are welcome! 😃
