### ISSUE TITLE
Make sub-grids use all available width for a large number of them -- possible?

### ISSUE THREAD

**Issue by noyannus** [aardappel/treesheets#607]
Is it possible to force all sub(-sub)-grids in a column or row to use all available width?

I'm on a project with by now 1.1k columns and >11k cells. Now I need to continue with the transposed sheet (transposing works), but all grids in a cell (or maybe only those where I've set the width manually, not sure) keep the width they had before transposing. That increases row height far too much, and going through a high number of grids and widen them manually is not something one looks forward to...

Also, is it possible to make a column expand horizontally (keeping the row's height), in the same way the bottom row expands as necessary for the given column width?

**Comment by aardappel** [comment]
There's no way to control width other than the "columns" setting, no.

What you might find handy is "Reset Column Widths" (Ctrl+Shift+W), which you can do on the whole sheet, at least from there it will be easy to consistently resize the columns from there.

**Comment by noyannus** [comment]
Thanks, I will try that.
