### ISSUE TITLE
TreeSheets freezes when I try to import file

### ISSUE THREAD

**Issue by Arkronus** [aardappel/treesheets#608]
OS: Windows 10

When I go to **File - Import From - XML** (or any other format) the program freezes when Open File dialog should appear

![изображение](https://github.com/aardappel/treesheets/assets/6567321/0e7a08d4-237f-4555-87c2-ac9dd54ff5c2)

**Comment by aardappel** [comment]
So it looks like the file dialog itself is freezing? (since part of it is already rendered).

So this happens with any of the "import" options, but not with normal "open" for example?

**Comment by t2b3** [comment]
Small note from my side: I could not reproduce the issue on Windows 10. Are you using the latest release from the GitHub page?

**Comment by Arkronus** [comment]
Looks like it was a problem with Windows. After reboot, it works ok.
