### ISSUE TITLE
FreeBSD: cmake install paths on non-linux

### ISSUE THREAD

**Issue by nunotexbsd** [aardappel/treesheets#614]
Updating from 7861249636 to latest commit 7ab85ae41dae31d62ceccfae530c5597e674df0c cmake need patching to install correctly into:

PREFIX/bin
PREFIX/share/docs/PKGNAME
PREFIX/share

Until 7861249636, the only change needed was:

```
-install(DIRECTORY TS/examples DESTINATION ${TREESHEETS_DOCDIR})
+install(DIRECTORY TS/examples DESTINATION ${CMAKE_INSTALL_DATADIR}/examples/${CMAKE_PROJECT_NAME})
```

At 7ab85ae41dae31d62ceccfae530c5597e674df0c it needs patch but runtime gives error bellow.

Am I missing something?
Thanks

```
--- CMakeLists.txt.orig 2024-03-24 04:56:12 UTC
+++ CMakeLists.txt
@@ -117,18 +117,23 @@ else()
     install(FILES linux/com.strlen.TreeSheets.desktop DESTINATION ${CMAKE_INSTALL_DATADIR}/applications)
     install(FILES linux/com.strlen.TreeSheets.xml DESTINATION ${CMAKE_INSTALL_DATADIR}/mime/packages)
 else()
-    set(TREESHEETS_BINDIR ${CMAKE_INSTALL_PREFIX})
-    set(TREESHEETS_DOCDIR ${CMAKE_INSTALL_PREFIX})
-    set(TREESHEETS_PKGDATADIR ${CMAKE_INSTALL_PREFIX})
+    include(GNUInstallDirs)
+    set(TREESHEETS_BINDIR ${CMAKE_INSTALL_BINDIR})
+    set(TREESHEETS_DOCDIR ${CMAKE_INSTALL_DOCDIR})
+    set(TREESHEETS_PKGDATADIR ${CMAKE_INSTALL_DATADIR}/${CMAKE_PROJECT_NAME})
 endif()

 install(TARGETS treesheets DESTINATION ${TREESHEETS_BINDIR})
 install(DIRECTORY TS/docs DESTINATION ${TREESHEETS_DOCDIR})
 install(FILES TS/readme.html DESTINATION ${TREESHEETS_DOCDIR})
-install(DIRECTORY TS/examples DESTINATION ${TREESHEETS_DOCDIR})
+install(DIRECTORY TS/examples DESTINATION ${CMAKE_INSTALL_DATADIR}/examples/${CMAKE_PROJECT_NAME})

 install(DIRECTORY TS/images DESTINATION ${TREESHEETS_PKGDATADIR})
 install(DIRECTORY TS/scripts DESTINATION ${TREESHEETS_PKGDATADIR})
+
+install(FILES linux/com.strlen.TreeSheets.svg DESTINATION ${CMAKE_INSTALL_DATADIR}/icons/hicolor/scalable/apps)
+install(FILES linux/com.strlen.TreeSheets.desktop DESTINATION ${CMAKE_INSTALL_DATADIR}/applications)
+install(FILES linux/com.strlen.TreeSheets.xml DESTINATION ${CMAKE_INSTALL_DATADIR}/mime/packages)

 # Install translations to correct platform-specific path.
 # See: https://docs.wxwidgets.org/trunk/overview_i18n.html#overview_i18n_mofiles
```

Error on run:
```
% treesheets
w
08:34:17: wxWidgets 3.2.4
l
08:34:17: locale: en_US.UTF-8
c
08:34:17: Error: can't open file 'images/icon16.png' (error 2: No such file or directory)
F
08:34:17: Error: Failed to load image from file "images/icon16.png".
c
08:34:17: Error: can't open file 'images/icon32.png' (error 2: No such file or directory)
F
08:34:17: Error: Failed to load image from file "images/icon32.png".
```

**Comment by nunotexbsd** [comment]
I don't think so from what I'm reading on https://wiki.freebsd.org/HFS

At version 7861249636 I didn't change values from CMakeLists.txt appart from sending examples to other dir, so it is a good start the check what changed.

**Comment by t2b3** [comment]
Sorry I meant Filesystem Hierarchy Standard.

**Comment by nunotexbsd** [comment]
FreeBSD Unix don't conform with FHS and it is the first time that I'm seing it being configured in cmake:

https://man.freebsd.org/cgi/man.cgi?hier(7)

**Comment by t2b3** [comment]
Does it help to replace `LINUX` with `BSD` in `CMakeLists.txt`  and to keep the original patch?
```
-install(DIRECTORY TS/examples DESTINATION ${TREESHEETS_DOCDIR})
+install(DIRECTORY TS/examples DESTINATION ${CMAKE_INSTALL_DATADIR}/examples/${CMAKE_PROJECT_NAME})
```

**Comment by nunotexbsd** [comment]
@t2b3 

It worked fine! I've run so many tests and even so I did missed something.

My test patch is:
```
--- CMakeLists.txt.orig 2024-03-28 08:00:11 UTC
+++ CMakeLists.txt
@@ -99,7 +99,7 @@ endif()
     OPTION(TREESHEETS_RELOCATABLE_INSTALLATION "Install data relative to the treesheets binary, instead of respecting the Filesystem Hierarchy Standard" OFF)
 endif()

-if(LINUX AND NOT TREESHEETS_RELOCATABLE_INSTALLATION)
+if(NOT LINUX AND NOT TREESHEETS_RELOCATABLE_INSTALLATION)
     include(GNUInstallDirs)

     set(TREESHEETS_BINDIR ${CMAKE_INSTALL_BINDIR})
@@ -125,7 +125,7 @@ install(FILES TS/readme.html DESTINATION ${TREESHEETS_
 install(TARGETS treesheets DESTINATION ${TREESHEETS_BINDIR})
 install(DIRECTORY TS/docs DESTINATION ${TREESHEETS_DOCDIR})
 install(FILES TS/readme.html DESTINATION ${TREESHEETS_DOCDIR})
-install(DIRECTORY TS/examples DESTINATION ${TREESHEETS_DOCDIR})
+install(DIRECTORY TS/examples DESTINATION ${CMAKE_INSTALL_DATADIR}/examples/${CMAKE_PROJECT_NAME})

 install(DIRECTORY TS/images DESTINATION ${TREESHEETS_PKGDATADIR})
 install(DIRECTORY TS/scripts DESTINATION ${TREESHEETS_PKGDATADIR})
```

So, for my understanding FreeBSD could be added to this block.

**Comment by t2b3** [comment]
Thanks for your reply! Happy to hear that it works.
One more question: Is it sufficient to patch the CMakeLists.txt in this way to make it work on FreeBSD.
I am curious whether it is needed to patch the install destination for `TS/examples`.

```
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 576cf3f..84d0f57 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -95,11 +95,11 @@ target_link_libraries(
 
 ########## TREESHEETS INSTALLATION SETTINGS ###############
 
-if(LINUX)
+if(LINUX OR FREEBSD)
     OPTION(TREESHEETS_RELOCATABLE_INSTALLATION "Install data relative to the treesheets binary, instead of respecting the Filesystem Hierarchy Standard" OFF)
 endif()
 
-if(LINUX AND NOT TREESHEETS_RELOCATABLE_INSTALLATION)
+if((LINUX OR FREEBSD) AND NOT TREESHEETS_RELOCATABLE_INSTALLATION)
     include(GNUInstallDirs)
 
     set(TREESHEETS_BINDIR ${CMAKE_INSTALL_BINDIR})
```

**Comment by nunotexbsd** [comment]
> +if(LINUX OR FREEBSD)

Adding FREEBSD like this doesn't work (all files get installed into cmake install prefix).

CMAKE_SYSTEM_NAME STREQUAL "FreeBSD" seems the right setting, don't know if a generic one exists for *bsd.

**Comment by t2b3** [comment]
Ok, what about `BSD` then directly? Sorry, you are completely right!
https://cmake.org/cmake/help/latest/manual/cmake-variables.7.html

**Comment by t2b3** [comment]
> > +if(LINUX OR FREEBSD)
> 
> Adding FREEBSD like this doesn't work (all files get installed into cmake install prefix).
> 
> CMAKE_SYSTEM_NAME STREQUAL "FreeBSD" seems the right setting, don't know if a generic one exists for *bsd.
> 
> Don't know if TREESHEETS_RELOCATABLE_INSTALLATION will have any use on FreeBSD...

Yes, I think it has its use case if you do not want to install it directly to the `/usr/` hierarchy, but e.g. only to install it somewhere in your home directory and/or if you want to keep everything in one folder and move it around. Then relocatable install is needed.

**Comment by nunotexbsd** [comment]
> +if(LINUX OR BSD)

Works perfectly.

Understand about TREESHEETS_RELOCATABLE_INSTALLATION.

Related to:
```
-install(DIRECTORY TS/examples DESTINATION ${TREESHEETS_DOCDIR})
+install(DIRECTORY TS/examples DESTINATION ${CMAKE_INSTALL_DATADIR}/examples/ {CMAKE_PROJECT_NAME})
```
It has to do with our hier and ports framework:

DATADIR gets expanded to PREFIX/share/PORTNAME.
DOCSDIR gets expanded to PREFIX/share/doc/PORTNAME.
EXAMPLESDIR gets expanded to PREFIX/share/examples/PORTNAME.

cmake apears to not have a variable for examples like it do for doc, so I've patched it.

**Comment by t2b3** [comment]
Ok :-) Thanks for your feedback! Is it okay for you to keep the patch at your (port) side?

**Comment by nunotexbsd** [comment]
Sure, not problem.

Thanks for help solving this issue.

**Comment by t2b3** [comment]
> Sure, not problem.
> 
> Thanks for help solving this issue.

You are welcome.
