### ISSUE TITLE
Chronicle the build process under debian wheezy using Jenkins

### ISSUE THREAD

**Issue by vo1stv** [aardappel/treesheets#62]
This is a feature request/offer.

I've set up a debian wheezy VM  with Jenkins support at http://access.vo1stv.ca:4444/job/treesheets

I've gone through 5 builds so far... seems to be having issues with the version of wxWidgets installed.

This is a VM snapshot that is completely disposable so feel free to test some of the features of Jenkins and experiment with how an automated test environment can help validate the algorithms.  I apologize for the sluggishness of the VM.. please be patient with it and check back periodically,  I plan to integrate this into the main host once I've gotten over the learning curve.

**Comment by aardappel** [comment]
Yeah, it needs a relatively recent version of wxWidgets, whatever comes with debian is not likely to be recent enough. You may need install that seperately, or build it as part of the CI job (though that will slow it down a lot).

What is your plan with this? I wouldn't mind someone taking care of CI, but using Travis may be a more permanent solution that doesn't require you to host anything.

**Comment by vo1stv** [comment]
My plan has been mostly to test drive the CI software.  

I agree, Travis fits the bill must better for GitHub hosted projects.  I just signed up, and I will register my fork there.
