### ISSUE TITLE
I propose a translation of the RU help file...

### ISSUE THREAD

**Issue by qua-rus** [aardappel/treesheets#646]
...including the Introduction.
[TreeSheets_Help.zip](https://github.com/aardappel/treesheets/files/15473023/TreeSheets_Help.zip)

**Comment by tobiolo** [comment]
Hello Aleksander, 
Thanks for your great work and your translation into Russian.
I commited the tutorial file in this commit https://github.com/aardappel/treesheets/commit/d6b97b9a32fb9739a81d335764c61772ca8ec21e and I am looking for a good place for the introduction file.
Thanks again! :+1: 
Best regards,
Tobias

**Comment by qua-rus** [comment]
1) I’ll check the translation again and maybe correct it... where should I send the result?

2) I would take on the task of translating the program interface into Russian, but the instructions in the file https://github.com/aardappel/treesheets/blob/master/TS/translations/readme_translations.txt did not give any results (I don’t do programming)...
- I installed the gettext package (Debian Linux);
- created the structure "translations/ru_RU"
- placed the ts.pot file in the "translations" directory
- in this directory ran the command:
msginit --input ts.pot --locale=ru_RU.UTF-8 --output=ru_RU/ts.po
... received the file "translations/ru_RU/ts.po"
- placed the merge.sh and compile.sh files from https://github.com/aardappel/treesheets/tree/master/TS/translations/fr_FR into the "translations/ru_RU" directory
... as I understand it, now in the ts.po file it is necessary to insert Russian translations into the "msgstr" lines (which I did for several lines).
But running merge.sh (contains the command: msgmerge --update --backup=numbered ts.po ../ts.pot) does not transfer my non-Russian translations from ts.po to ts.pot... Further actions are inappropriate.
What should I do?

**Comment by tobiolo** [comment]
> But running merge.sh (contains the command: msgmerge --update --backup=numbered ts.po ../ts.pot) does not change the ts.po and ts.pot files... I considered further actions inappropriate, because . After reading man msgmerge I don’t quite understand what to do (I don’t do programming)...
> 
> What should I do?

The first steps were correct. 
You initialized a new translation and took the template (pot) to derive a translation file (po) from it. Now you would need to "compile" that translation into the binary format (mo) with msgfmt. There should be a compile.sh script that generates the mo file. The msgmerge is to update the language translation file po when the template pot has changed. Then the translation has to be updated and afterwards be compiled again with msgfmt / compile.sh. Did this help you?

**Comment by tobiolo** [comment]
> 1) I’ll check the translation again and maybe correct it... where should I send the result?
> 
Please feel free to upload it here if you are not familiar with git and GitHub Pull Requests.

**Comment by qua-rus** [comment]
1... Thank you, I’ll definitely figure it out with git a little later.

**Comment by qua-rus** [comment]
> 2...
> The first steps were correct.
> ...
> Did this help you?


2... Thank you, I understand the purpose of the command in the merge.sh file, I will proceed further.

**Comment by qua-rus** [comment]
Brought the Introduction into a human-readable form.
[intro-ru.cts.zip](https://github.com/user-attachments/files/15536841/intro-ru.cts.zip)

**Comment by qua-rus** [comment]
Brought the Introduction into a human-readable form.
[intro-ru.cts.zip](https://github.com/user-attachments/files/15537642/intro-ru.cts.zip)

**Comment by qua-rus** [comment]
Brought the Interactive Guide into a human-readable form.
[tutorial-ru.cts.zip](https://github.com/user-attachments/files/15538778/tutorial-ru.cts.zip)
I placed the file tutorial-ru.cts in the directory:
/var/lib/flatpak/app/com.strlen.TreeSheets/current/active/files/share/doc/treesheets/examples/
...on F1 I opened an Interactive Guide in Russian.

**Comment by qua-rus** [comment]
I took up the translations in the ts.po file. Completed a partial translation and compiled it into a ts.mo file. Moved ru_RU/ts.mo to the directory
/var/lib/flatpak/app/com.strlen.TreeSheets/current/x86_64/stable/files/share/locale/
The translation works... but in the translation catalog there are broken links to other language translations... maybe. you might be interested in:
![Снимок экрана_2024-06-03_22-42-26](https://github.com/aardappel/treesheets/assets/91870946/13cacc33-c369-44a3-a4db-88a4752f54ae)

**Comment by tobiolo** [comment]
Thanks for the translation work! 

I can only guess that the Flatpak locale package for TreeSheets is split into packages for each language.
https://github.com/flatpak/flatpak/issues/5560

**Comment by qua-rus** [comment]
Thank you, another question...
The "&" character appears frequently in the ts.po (and ts.pot) file.
It is not always possible to translate a string so as to preserve the identical location of the "&" character in the translation string.
Besides this, I see the same lines, with the only difference being the presence/absence of the "&" character.
In addition, this character is missing in many lines...
What is the purpose of the "&" character and how important is its presence (and location) in translation strings?

**Comment by qua-rus** [comment]
> Brought the Interactive Guide into a human-readable form. [tutorial-ru.cts.zip](https://github.com/user-attachments/files/15538778/tutorial-ru.cts.zip) I placed the file tutorial-ru.cts in the directory: /var/lib/flatpak/app/com.strlen.TreeSheets/current/active/files/share/doc/treesheets/examples/ ...on F1 I opened an Interactive Guide in Russian.

**Comment by qua-rus** [comment]
> Brought the Interactive Guide into a human-readable form.

I noticed a functional inaccuracy in paragraph 17.
[Uploading tutorial-ru.cts.zip…]()

**Comment by qua-rus** [comment]
> Brought the Interactive Guide into a human-readable form.

I noticed a functional inaccuracy in paragraph 17.
[tutorial-ru.cts.zip](https://github.com/user-attachments/files/15592840/tutorial-ru.cts.zip)

**Comment by tobiolo** [comment]
The & are so-called mnemonics, see
e.g. https://www.wxwidgets.org/docs/tutorials/using-mnemonics/ for more details.

**Comment by tobiolo** [comment]
> > Brought the Interactive Guide into a human-readable form.
> 
> I noticed a functional inaccuracy in paragraph 17. [tutorial-ru.cts.zip](https://github.com/user-attachments/files/15592840/tutorial-ru.cts.zip)

Pushed as commit. Thanks!

**Comment by qua-rus** [comment]
> The & are so-called...

Thank you.

**Comment by qua-rus** [comment]
Brought the Introduction into a human-readable form.
[intro-ru.cts.zip](https://github.com/user-attachments/files/15537642/intro-ru.cts.zip)
