### ISSUE TITLE
Does TS honor attribute-sets in the xml import?

### ISSUE THREAD

**Issue by noyannus** [aardappel/treesheets#648]
Does TS honor `attribute-sets` in the xml import?

I try to set the set like so
```
<xsl:attribute-set name="foo">
  <xsl:attribute name="colorbg">12345678</xsl:attribute>
</xsl:attribute-set>
```
and call it with ` <cell use-attribute-sets="foo">` and the background is white. Importing a background color with `<cell colorbg="12345678">` works, though.

On a more general note: Does TS support only a subset of xml?

**Comment by aardappel** [comment]
TS xml import imports the flavor of xml that is the same as the format it outputs.

There is no such thing as "standard" or "subset" of xml. xml is a generic format like JSON that can store many kinds of data, depending on the (implied or given) schema. What you have there is xsl which is web specific thing on top of xml.

We also have html output which does confirm to web standards.

**Comment by noyannus** [comment]
Ah, my bad. Of course, TS does not have to touch the transforming xslt stylesheet.
