### ISSUE TITLE
Need help wth MacOS

### ISSUE THREAD

**Issue by vo1stv** [aardappel/treesheets#65]
I'm working on extending Travis support to include osx and it's going well.

The grunt work is done; the attached log shows that the build fails due to presumed location of wx being in /usr/local/lib/wx

https://s3.amazonaws.com/archive.travis-ci.org/jobs/130740320/log.txt

I'd appreciate a osx  developer to review my .travis.xml file in the 'allplatforms' branch of my fork to either:
1) install wxWidgets to /usr/local/lib/wx (not recommended); or
2) point the include directive to  /Users/travis/build/vo1stv/treesheets/wxWidgets/build_osx

**Comment by aardappel** [comment]
Thanks for working on this. Not entirely sure how to solve this, this has the steps I use on OS X:
https://github.com/aardappel/treesheets/blob/master/README.txt

**Comment by vo1stv** [comment]
No problem.  OSX support is something I haven't had any hands on practice with, so this has been a good learning experience.  I just started a new build and will check on it in the morning.  It's supposed to install includes for wxWidgets to treesheets/src/wx. If that works and compiles I'd be surprised.  The "brew install wxmac" looked promising but fails looking for "wx/setup.h"

**Comment by vo1stv** [comment]
I've traced the problem to a hard-coded support for version 3.0 of the wxWidgets, but the latest version is 3.1.  The solution requires sticking with the 3.0 version and eventually editing  project.pbxproj to support future versions of wxWidgets.  I can't solve this is a politically correct way because I haven't got an editor for *.pbxproj (I'm assuming they are created by an IDE of some type).  I don't really want to commit a hack by editing the file with pico if that's not the workflow.

If someone does edit the pbxproj,  consideration should be given to using --prefix to allow it to be built without sudo rights.

The discussion for and against install wxWidgets to /usr/local/lib/wx originates here:
https://wiki.wxwidgets.org/Compiling_wxWidgets_using_the_command-line_%28Terminal%29

**Comment by aardappel** [comment]
`.pbxproj` is Xcode, and can be built without an IDE (thru `xcodebuild`). The wxWidgets library filenames appear to encode the version, so I am not sure if there's a good way around this.. other than updating the project files whenever versions change.

I suppose it may be easiest if I update the project files?

**Comment by vo1stv** [comment]
Certainly the things I have learned have been by building .pbxproj is Xcode, without an IDE thru xcodebuild. 

I suppose it may be easiest if you update the project files.  My attempts at manually editing them using pico result in the .pbxproj failing integrity checks.  As you said, The wxWidgets library filenames appear to encode the version, so I am not sure if there's a good way around this.. other than updating the project files whenever versions change.  

A programmatic way of changing the project files that preserves their integrity would be the ideal solution,

**Comment by aardappel** [comment]
I just added this commit, which should help: https://github.com/aardappel/treesheets/commit/6e0aa345d2d7daa185ba3209835b621b42955e42

**Comment by vo1stv** [comment]
That worked like a charm.
