### ISSUE TITLE
Latest binaries mising libtiff.so.5 

### ISSUE THREAD

**Issue by noyannus** [aardappel/treesheets#651]
On Kubuntu 24.04 / KDE 5.27.11, the latest binaries won't run.` libtiff.so.5` is missing.

```
root@osboxes:/home/osboxes# /home/osboxes/Downloads/TreeSheets-relocatable_g/treesheets
/home/osboxes/Downloads/TreeSheets-relocatable_g/treesheets: error while loading shared libraries: libtiff.so.5: cannot open shared object file: No such file or directory
root@osboxes:/home/osboxes# /home/osboxes/Downloads/TreeSheets-relocatable_clang/treesheets
/home/osboxes/Downloads/TreeSheets-relocatable_clang/treesheets: error while loading shared libraries: libtiff.so.5: cannot open shared object file: No such file or directory
root@osboxes:/home/osboxes# apt install libtiff.so.5
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package libtiff.so.5
E: Couldn't find any package by glob 'libtiff.so.5'
root@osboxes:/home/osboxes#

```

**Comment by noyannus** [comment]
That `latest` looks suspicious. 24.04 is the current LTS out in the wild. Kubuntu 22 ended with [23.04 on 2023-04-20](https://en.wikipedia.org/wiki/Kubuntu#Releases). Or am I misunderstanding you? 

With [actions/runner-images](https://github.com/actions/runner-images) I am not familiar, but if they really are still wresting with 23, not to mention 24... Could the [openSUSE Build Service](https://build.opensuse.org/) (or another OBS instance) be an alternative?

>[The Open Build Service](https://openbuildservice.org/) (OBS) is a generic system to build and distribute binary packages from sources in an automatic, consistent and reproducible way. You can release packages as well as updates, add-ons, appliances and entire distributions for a wide range of operating systems and hardware architectures.
>
>The openSUSE project runs it's own instance at https://build.opensuse.org/
([source](https://en.opensuse.org/Portal:Build_Service))

Wikipedia on the [workflow](https://en.wikipedia.org/wiki/Open_Build_Service#Workflow_and_usage)


re `libtiff`: That was a desperate attempt so get it running...

**Comment by aardappel** [comment]
We are not Linux only, we need a cross platform build integrated with github.

Did you try `apt install libtiff5` ?

**Comment by noyannus** [comment]
Tried `libtiff5-dev` and `libtiff-tools`, no luck.

re build: OBS can be [linked](https://openbuildservice.org/help/manuals/obs-user-guide/cha.obs.concepts#concept_scm_integration) with [github](https://openbuildservice.org/help/manuals/obs-user-guide/cha.obs.scm_ci_workflow_integration#sec.obs.obs_scm_ci_workflow_integration.setup) so GH pushes and starts the build etc. That could take care of a host of Linux distros.

Not sure how to understand the FAQ entry about [Windows builds](https://en.opensuse.org/openSUSE:Build_Service_FAQ#Can_the_Open_Build_Service_build_packages_for_Windows_OS_?) (page last edited 12/2022)
>Windows executables can be produced using a cross-compiler, such as the mingw suite. Because the build target most commonly still is a Linux distribution, the binaries still end up in a .rpm or .deb package. 

That means the product for windows only needs upacking repacking the .rpm/.deb -?

**Comment by georgeraraujo** [comment]
> Tried `libtiff5-dev` and `libtiff-tools`, no luck.

Try [these instructions](https://askubuntu.com/questions/1513113/the-wps-pdf-reader-is-not-working-on-ubuntu-24-04).

**Comment by noyannus** [comment]
Some version also needed `sudo ln -s libpcre2-16.so.0 libpcre2-32.so.`

Closing as resolved.
