### ISSUE TITLE
Suggestion: Version number in "About..." window, semantic versioning

### ISSUE THREAD

**Issue by noyannus** [aardappel/treesheets#665]
When dealing with several TS installations, it becomes very cumbersome to keep track if the new releases come frequently. And with  >1 release/day, the date is not specific enough. Please consider including the exact version number in the "About..." dialog. 

Even better, and much easier to "visually grep" would be a semantic numbering, of the releases only, because of smaller and visually chunked much smaller numbers. It's much easier to see at a clance that `nn.nn.03` is not `nn.nn.04` than `nnnnnnnnnn` is not `nnmmmmmmmm`.

edit: A discriminiation between g++ and clang++ would also be helpful, just in case...

(Background: I ran into a problem where two seemingly identical versions of TS (same version number/same day, Flatpak, installed via Discover, one on Tumbleweed, one on a fresh Kubuntu 24) could not open each other's saved files because of "newer version". Not sure still if EBKAC so no issue opened.)

**Comment by aardappel** [comment]
We have the current simplistic release system simply to cut down on manual "release management" steps, it is all automated. That includes updating About dialogs in the source code or trying to maintain some logical semantic versioning.

Most people don't, or shouldn't run multiple installs.

**Comment by noyannus** [comment]
I understand. 

The dual install is because on the main work Tumbleweed the `Open` and `Save` dialogs don't enter `~/`. (Permissions all `770` from there down, latest available Flatpak, double click opens `*.cts`. I only wanted to open an issue after more investigation.) Hence a second TS in a less snappy Kubuntu VM for the infrequent xslt transformations that need `Open` and `Save`/`Save-as`.
