### ISSUE TITLE
FreeBSD: error: call to deleted function 'from_chars'

### ISSUE THREAD

**Issue by nunotexbsd** [aardappel/treesheets#686]
FreeBSD, Clang 18.1.6

Updating from 9365612553 to 10101933522:

```
FAILED: CMakeFiles/lobster.dir/lobster/src/builtins.cpp.o
/usr/bin/c++ -DWXUSINGDLL -D_FILE_OFFSET_BITS=64 -D_THREAD_SAFE -D__WXGTK__ -I/wrkdirs/usr/ports/deskutils/treesheets/work/treesheets-10101933522/lobster/include -I/wrkdirs/usr/ports/deskutils/treesheets/work/tre
esheets-10101933522/lobster/src -I/wrkdirs/usr/ports/deskutils/treesheets/work/treesheets-10101933522/lobster/external/libtcc -isystem /usr/local/lib/wx/include/gtk3-unicode-3.2 -isystem /usr/local/include/wx-3.2
 -O2 -pipe -fstack-protector-strong -fno-strict-aliasing -pthread -O2 -pipe -fstack-protector-strong -fno-strict-aliasing   -DNDEBUG -std=gnu++20 -MD -MT CMakeFiles/lobster.dir/lobster/src/builtins.cpp.o -MF CMak
eFiles/lobster.dir/lobster/src/builtins.cpp.o.d -o CMakeFiles/lobster.dir/lobster/src/builtins.cpp.o -c /wrkdirs/usr/ports/deskutils/treesheets/work/treesheets-10101933522/lobster/src/builtins.cpp
In file included from /wrkdirs/usr/ports/deskutils/treesheets/work/treesheets-10101933522/lobster/src/builtins.cpp:15:
In file included from /wrkdirs/usr/ports/deskutils/treesheets/work/treesheets-10101933522/lobster/src/lobster/stdafx.h:85:
/wrkdirs/usr/ports/deskutils/treesheets/work/treesheets-10101933522/lobster/src/lobster/string_tools.h:169:20: error: call to deleted function 'from_chars'
  169 |         auto res = from_chars(sv.data(), sv.data() + sv.size(), val);
      |                    ^~~~~~~~~~
/wrkdirs/usr/ports/deskutils/treesheets/work/treesheets-10101933522/lobster/src/builtins.cpp:501:18: note: in instantiation of function template specialization 'parse_float<double>' requested here
  501 |         auto f = parse_float<double>(sv, &end);
      |                  ^
/usr/include/c++/v1/__charconv/from_chars_integral.h:37:19: note: candidate function has been explicitly deleted
   37 | from_chars_result from_chars(const char*, const char*, bool, int = 10) = delete;
      |                   ^
/usr/include/c++/v1/__charconv/from_chars_integral.h:223:1: note: candidate template ignored: requirement 'is_integral<double>::value' was not satisfied [with _Tp = double]
  223 | from_chars(const char* __first, const char* __last, _Tp& __value) {
      | ^
/usr/include/c++/v1/__charconv/from_chars_integral.h:229:1: note: candidate function template not viable: requires 4 arguments, but 3 were provided
  229 | from_chars(const char* __first, const char* __last, _Tp& __value, int __base) {
      | ^          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

```
Full log: 
[15amd64_treesheets-1.0.20240725.log](https://github.com/user-attachments/files/16389016/15amd64_treesheets-1.0.20240725.log)

Any clues?
Thanks

**Comment by tobiolo** [comment]
Hello @nunotexbsd 
I guess this has to do with lobster and might have to be fixed there? @aardappel What do you think? 
Best regards
Tobias

**Comment by aardappel** [comment]
Your Clang is more recent than what we build with on CI for e.g. Linux, that implements `from_chars` just fine, so it seems you are building with an outdated C++ standard lib. It appears to be in `/usr/include/c++/v1`.

Your `from_chars` is explicitly deleted, which I presume they did before it was implemented.

Also worth checking the CMakeList.txt, which presumable is going to build thru the `if(UNIX)` path and doesn't know about BSD specifically, so may set the wrong standard lib?

It appears to be using `-std=gnu++20` which I have no idea if that is the correct option here.

**Comment by nunotexbsd** [comment]
`-std=gnu++20` comes from https://github.com/aardappel/treesheets/blob/a05a34734135b3899b6c742df8a9c1338fc168b2/CMakeLists.txt#L29

I also checked build results from releases 14.1/Clang 18.1.6, 14.0/Clang 16.0.6 and 13.3/Clang 17.0.6 all with same error.

My plan is to try a commit by commit build to know exacly where it start to fail.
I can try lowering c++ STD and check if it changes anything.

Thanks

**Comment by nunotexbsd** [comment]
(...)

I can confirm that it stop building at [9850843724](https://github.com/aardappel/treesheets/releases/tag/9850843724) what also confirms what being said about lobster update.

**Comment by nunotexbsd** [comment]
@aardappel 

Hello,

Just found https://github.com/Stellarium/stellarium/issues/3656 that might address this problem.
Could you take a look ang give your opinion?

I'm gathering all info I can so I open a FreeBSD PR.

Thanks

**Comment by aardappel** [comment]
The code already has a fallback and looks like this:

```
template<typename T> T parse_float(string_view sv, const char **end = nullptr) {
    // FIXME: Upgrade compilers for these platforms on CI.
    #if defined(__APPLE__) || defined(__ANDROID__) || defined(__EMSCRIPTEN__)
        auto &term = *(char *)(sv.data() + sv.size());
        auto orig = term;
        term = 0;
        auto v = (T)strtod(sv.data(), (char **)end);
        term = orig;
        return v;
    #else
        T val = 0;
        auto res = from_chars(sv.data(), sv.data() + sv.size(), val);
        if (end) *end = res.ptr;
        return val;
    #endif
}
```

So why not just add a `|| defined(__FreeBSD__)` ?

**Comment by nunotexbsd** [comment]
@aardappel 

Hello!

I can confirm that this way I get treesheets compiled ok. It also runs without any issue.
Could we let this PR open for a couple of days as I'm waiting for FreeBSD devs opinion on this?

Thanks

**Comment by nunotexbsd** [comment]
Looks that this workaround should be used. At the moment, from_chars is only implemented for integers, in libc++.

See also:
https://lists.freebsd.org/archives/freebsd-current/2024-August/006279.html

Thanks

**Comment by aardappel** [comment]
Added here: https://github.com/aardappel/treesheets/commit/68b11660e755a625bf77b012f5e0faa8bd79bbf5

Also upstream: https://github.com/aardappel/lobster/commit/73db3918b066592e49bbb60fb5449fdacc33f88e
