### ISSUE TITLE
Ubuntu 16.04: no shortcut and icons

### ISSUE THREAD

**Issue by Deevad** [aardappel/treesheets#73]
Hi,
Thank you for Treesheets. I installed it via Ubuntu 16.04 LTS official repositories (64bit) and I had no icon or shortcut in menu. I guess it is related to the work of the Debian packager. The software launch from terminal. 

**Workaround:** I did this fix for my local installation:

Add a /home/<yourusername>/.local/share/application/treesheets.desktop file with this inside this (customise the path for the icon) :
```
[Desktop Entry]
Name=Treesheets
Exec="treesheets" %U
GenericName=Treesheets
Comment=Free Form Data Organizer.
Type=Application
Icon=/home/<yourusername>/path/to/the/icon/treesheets.svg
Categories=Accessories;
```

For the icon, I made this one ; consider it as public domain:
![2017-02-28_screenshot_093227](https://cloud.githubusercontent.com/assets/4021867/23397477/f6e03b14-fd98-11e6-8b7f-ba7cd2542d6e.png)
and the source SVG: 
[treesheets_svg.zip](https://github.com/aardappel/treesheets/files/806101/treesheets_svg.zip)

_( note; the icon is a derivation of Binaree Tree by TheStructorr on https://openclipart.org/detail/216277 , public domain too )_

**Comment by aardappel** [comment]
Thanks for the icon!

There was already a treesheets.desktop file, but its `icon` entry didn't point to a file, or maybe the file as a whole doesn't get used, not sure.

I added your icon: https://github.com/aardappel/treesheets/commit/786e00fc9dc945c15d4df90958cab81bf6fc7668

**Comment by Deevad** [comment]
Thank you @aardappel !

**Comment by dumblob** [comment]
@Deevad do you know how to get in touch with the Debian/Ubuntu packager? I have the same issue, but I thought that @aardappel is the packager, but it seems not to be the case.

**Comment by Deevad** [comment]
@dumblob : Hi, I guess it's the address I can be read in the *.deb package 's changelog. I'm pasting it under as a screenshot to protect the email of the packager:

![2017-03-08_screenshot_115708_net](https://cloud.githubusercontent.com/assets/4021867/23701333/9e0d9c34-03f6-11e7-8cec-7a94ceda54c3.jpg)

**Comment by dumblob** [comment]
Thanks @Deevad, I'll send an email to them. By the way nice icon :+1:.

**Comment by Deevad** [comment]
Thank you! and thanks for contacting them.

**Comment by aardappel** [comment]
Thanks! Yes, I am not involved in any packaging. If someone could check the icon shows up by default, that be great.

**Comment by infinity0** [comment]
Hey, I think I fixed this in May 2016 https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=818965 which is why it's not in Ubuntu 2016.04. It will probably be in the next version.

**Comment by dumblob** [comment]
@infinity0 thank you for fast response and explanation. Is there any supported (including auto-updates, etc.) way how to get the version earlier on Ubuntu? PPA seems an overkill for that.

**Comment by Deevad** [comment]
@infinity0 : Thank you for this maintenance! 

@dumblob : Maybe compiling? On the [AUR PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=treesheets-git) building receipe of Treesheets is written a couple of good hint about where to copy/install the built files. But maybe still too complex and time consuming to adapt it to a simple 16.04 bash build script. I'm fine with the version on the package with manual fix for icon/*.desktop so far :-)

**Comment by dumblob** [comment]
@Deevad well, I wanted to avoid https://github.com/jordansissel/fpm this time, but it seems Debian/Ubuntu packaging system still has those old, well-known sharp edges :cry:.
