### ISSUE TITLE
[macOS] multiple issues in '11825716028' release

### ISSUE THREAD

**Issue by core-code** [aardappel/treesheets#758]
previous macOS versions had proper version numbers that could be inspected in the Finder, both CFBundleVersion and CFBundleShortVersionString. in the new release both version numbers are missing.

the previous releases were proper universal binaries for both Intel and ARM Macs. the new one only works on ARM Macs.

the previous releases properly annotated its minimum system requirements ( LSMinimumSystemVersion ) as 10.15. the new release will just misbehave when launched on an "too early" system.

it basically looks like the whole Info.plist got replaced with a non-functioning in the new release. since "CFBundleDocumentTypes" is also missing now, it is unclear if double-clicking saved files will still work.

also, the bundle identifier changed from dot3labs.TreeSheets to com.strlen.TreeSheets and the name changed from TreeSheets to treesheets, was this on purpose?

**Comment by core-code** [comment]
<img width="386" alt="Screenshot 2024-11-14 at 11 26 45" src="https://github.com/user-attachments/assets/1d3b5c7a-2fff-4d93-af11-66e2b6c8869e">
<img width="382" alt="Screenshot 2024-11-14 at 11 26 39" src="https://github.com/user-attachments/assets/d5c426bd-d3e1-4baa-a127-498cc27d79e2">

**Comment by aardappel** [comment]
@tobiolo

**Comment by tobiolo** [comment]
I readded some of the missing nodes in the Plist, see https://github.com/aardappel/treesheets/pull/759

**Comment by tobiolo** [comment]
I guess the identifier is the reverse DNS, so I took the one from the official homepage, same as for the FlatPak.

**Comment by core-code** [comment]
thanks. i see the "11842730555" release is better than the last try. i can confirm that the issue with the version numbers has been resolved.

however:
1.) this is still a AppleSilicon-only build while releases prior to 11825716028 did run fine on Intel-Macs too
2.) it was compiled against the macOS 14 SDK so this won't even run on macOS 13:
![Screenshot 2024-11-14 at 22 34 55](https://github.com/user-attachments/assets/4f9b671a-cad0-4ea4-97e0-e593b94d7a92)

**Comment by aardappel** [comment]
MacOS 13 is from 2013.. I am not sure how much sense it makes for us to support OSes that far back unless it was trivial.

We should probably still support Intel if possible, though, if this is possible on CI.

**Comment by core-code** [comment]
i am talking about macOS 13 not Mac OS 10.13.

i.e. it will not run on systems that did not do this years macOS 15 and last years macOS 14 upgrade

**Comment by aardappel** [comment]
I was talking about neither, I was referring to the Darwin version haha.
Apple made a nice mess of versioning.

But yes we should support a 2022 OS.

**Comment by core-code** [comment]
> Apple made a nice mess of versioning.

indeed, and everything else too ;-)

**Comment by tobiolo** [comment]
Does it work now with the latest release?

**Comment by core-code** [comment]
all seems fine now, it is again an universal binary and should work back to 10.15. thanks
