### ISSUE TITLE
IDAT error for TS/images/nuvola/dropdown/bookcase.png

### ISSUE THREAD

**Issue by senderghost** [aardappel/treesheets#78]
Hello.

I noticed following error(s), when treesheets (3fc681cf5e3b28578e3214fe0fe973e187fb83f1) application runs from console:
```
% treesheets
w
20:08:50: wxWidgets 3.0.2
l
20:08:50: locale: C
c
20:08:50: content scale: 1.000000
I
20:08:50: Warning: IDAT: invalid distance too far back
C
20:08:50: Error: Couldn't load a PNG image - file is corrupted or not enough memory.
F
20:08:50: Error: Failed to load image from file "/usr/local/share/treesheets/images/nuvola/dropdown/bookcase.png".
```
It's for [bookcase.png](https://github.com/aardappel/treesheets/raw/aba59d2cedffdd812437d4086c718781eee276a2/TS/images/nuvola/dropdown/bookcase.png) image in aba59d2cedffdd812437d4086c718781eee276a2 commit.

The [identify](http://www.imagemagick.org/script/identify.php) application (from [ImageMagick](http://www.imagemagick.org) [tools](http://www.imagemagick.org/script/command-line-tools.php)) may report information about incomplete or corrupt image(s). The (stderr) output of it was following (for "*.png" files in [TS](https://github.com/aardappel/treesheets/tree/3fc681cf5e3b28578e3214fe0fe973e187fb83f1/TS) directory):
```
% cd TS && find * -iname "*.png" -exec identify -verbose {} > /dev/null "+"
TS: IDAT: invalid distance too far back `images/nuvola/dropdown/bookcase.png' @ error/png.c/MagickPNGErrorHandler/1644.
% sha256 images/nuvola/dropdown/bookcase.png
SHA256 (images/nuvola/dropdown/bookcase.png) = 0df3b69907b3315aea8cb5bb49220d307ce7e5a3771c20561609a1687f4e863d
```

Looks like, this is the same IDAT error, which was for [bookcase.png](https://github.com/aardappel/treesheets/raw/d4b2923b361c6d67fbb1bd208646007e85dc16f1/TS/images/nuvola/dropdown/bookcase.png) in d4b2923b361c6d67fbb1bd208646007e85dc16f1 commit:
```
% wget -q https://github.com/aardappel/treesheets/raw/d4b2923b361c6d67fbb1bd208646007e85dc16f1/TS/images/nuvola/dropdown/bookcase.png
% sha256 bookcase.png
SHA256 (bookcase.png) = b088cee52d657ab35a8a3a23e1d7441fea4653c1ed844fcedd7a042b4f990e6e
% identify -verbose bookcase.png > /dev/null
dropdown: IDAT: invalid distance too far back `bookcase.png' @ error/png.c/MagickPNGErrorHandler/1644.
```

It was [fixed](https://github.com/aardappel/treesheets/raw/6f247cc828c979b079659689e2f1e4703e46a04c/TS/images/nuvola/dropdown/bookcase.png) by @prurigro in 6f247cc828c979b079659689e2f1e4703e46a04c commit (#21 pull request).

**Comment by senderghost** [comment]
I also checked other images from [Nuvola icon set](https://web.archive.org/web/http://www.icon-king.com/projects/nuvola/) (from web archive).
The result is following:
```
% wget -q https://web.archive.org/web/http://www.icon-king.com/files/nuvola-1.0.tar.gz
% sha256 nuvola-1.0.tar.gz
SHA256 (nuvola-1.0.tar.gz) = 7078c9a3d39951fe36f3e0e54494216737c10514b34e31ff13052c516f99b932
% tar -xf nuvola-1.0.tar.gz
% sha256 nuvola/48x48/apps/bookcase.png
SHA256 (nuvola/48x48/apps/bookcase.png) = 0df3b69907b3315aea8cb5bb49220d307ce7e5a3771c20561609a1687f4e863d
% cd nuvola && find * -iname "*.png" -exec identify -verbose {} > /dev/null "+"
nuvola: IDAT: invalid distance too far back `128x128/apps/bookcase.png' @ error/png.c/MagickPNGErrorHandler/1644.
nuvola: IDAT: invalid distance too far back `128x128/mimetypes/bc.png' @ error/png.c/MagickPNGErrorHandler/1644.
nuvola: IDAT: invalid distance too far back `16x16/apps/bookcase.png' @ error/png.c/MagickPNGErrorHandler/1644.
nuvola: IDAT: invalid distance too far back `16x16/mimetypes/bc.png' @ error/png.c/MagickPNGErrorHandler/1644.
nuvola: IDAT: invalid distance too far back `22x22/apps/bookcase.png' @ error/png.c/MagickPNGErrorHandler/1644.
nuvola: IDAT: invalid distance too far back `22x22/mimetypes/bc.png' @ error/png.c/MagickPNGErrorHandler/1644.
nuvola: IDAT: invalid distance too far back `32x32/apps/bookcase.png' @ error/png.c/MagickPNGErrorHandler/1644.
nuvola: IDAT: invalid distance too far back `32x32/mimetypes/bc.png' @ error/png.c/MagickPNGErrorHandler/1644.
nuvola: IDAT: invalid distance too far back `48x48/apps/bookcase.png' @ error/png.c/MagickPNGErrorHandler/1644.
nuvola: IDAT: invalid distance too far back `48x48/mimetypes/bc.png' @ error/png.c/MagickPNGErrorHandler/1644.
nuvola: IDAT: invalid distance too far back `64x64/apps/bookcase.png' @ error/png.c/MagickPNGErrorHandler/1644.
nuvola: IDAT: invalid distance too far back `64x64/mimetypes/bc.png' @ error/png.c/MagickPNGErrorHandler/1644.
```
So, bc.png and bookcase.png images have such IDAT error(s).

I found, that some 128x128 version of [bookscase.png](https://commons.wikimedia.org/wiki/File:Nuvola_apps_bookcase.png) was added to [Wikimedia Commons](https://commons.wikimedia.org). But then someone added another version of it with comment: "pngcrushed".
The check shows, that "pngcrushed" version don't have IDAT error:
```
% wget -q https://upload.wikimedia.org/wikipedia/commons/archive/3/33/20060821190113%21Nuvola_apps_bookcase.png
% sha256 20060821190113\!Nuvola_apps_bookcase.png
SHA256 (20060821190113!Nuvola_apps_bookcase.png) = c2e3247de84ddd67712647d84d23dab15b3437eb0b19cfb48bfa7345cc83569c
% identify -verbose 20060821190113\!Nuvola_apps_bookcase.png > /dev/null && echo ok || echo not ok
wikimedia: IDAT: invalid distance too far back `20060821190113!Nuvola_apps_bookcase.png' @ error/png.c/MagickPNGErrorHandler/1644.
not ok
% wget -q https://upload.wikimedia.org/wikipedia/commons/archive/3/33/20070629085008%21Nuvola_apps_bookcase.png
% sha256 20070629085008\!Nuvola_apps_bookcase.png 
SHA256 (20070629085008!Nuvola_apps_bookcase.png) = 6795a732b956ee610abb245998736427339b635b07a394e79e6922f9844e8643
% identify -verbose 20070629085008\!Nuvola_apps_bookcase.png > /dev/null && echo ok || echo not ok
ok
```

Looks like, the [pngcrush](https://pmt.sourceforge.io/pngcrush/) application may fix IDAT error(s) for *.png image(s).

I added fixed [bookcase.png](https://github.com/senderghost/treesheets/raw/8e1a9e76d1886e74c3df29e89cfc0cd4c948315b/TS/images/nuvola/dropdown/bookcase.png) image to senderghost/treesheets@8e1a9e76d1886e74c3df29e89cfc0cd4c948315b commit. The bookcase.png image was checked and fixed with using following commands (CPU time output was skipped):
```
% identify -version | head -1
Version: ImageMagick 6.9.8-6 Q16 amd64 2017-05-27 http://www.imagemagick.org
% identify -verbose bookcase.png > /dev/null
dropdown: IDAT: invalid distance too far back `bookcase.png' @ error/png.c/MagickPNGErrorHandler/1644.
% pngcrush -version
 pngcrush 1.8.11, uses libpng 1.6.29+apng and zlib 1.2.8
 Check http://pmt.sf.net/
 for the most recent version.
% pngcrush -q -ow -brute -fix bookcase.png
  Recompressing IDAT chunks in bookcase.png
   Total length of data found in critical chunks            =      3783
   Best pngcrush method        = 114 (ws 14 fm 1 zl 9 zs 0) =      3728
% identify -verbose bookcase.png > /dev/null && echo ok
ok
```

To @aardappel:
I can create pull request for this, if needed.
Perhaps, someone know about other way(s) how to fix this issue. For example, there is alternative [48x48 bookcase image](https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Nuvola_apps_bookcase.svg/48px-Nuvola_apps_bookcase.svg.png), created from [SVG format](https://commons.wikimedia.org/wiki/File:Nuvola_apps_bookcase.svg) by other author(s) on Wikimedia Commons. But (current, from 3 September 2007) alternative bookcase image have some visual differences.

**Comment by aardappel** [comment]
Hey, thanks for researching this!

Yes, the previous fix was for the lower res version of that image, I never would have guessed that the higher res version has the same problem, I thought it was an actual corruption. I guess there is a bad encoder out there. Not sure why it would apply to some images and not others.

Please make a PR, I'll happily merge it.
