### ISSUE TITLE
Add versioned tarballs on GitHub

### ISSUE THREAD

**Issue by baimafeima** [aardappel/treesheets#83]
Hello Wouter, could you add tagged releases (versioned tarballs) here on GitHub as well?

**Comment by aardappel** [comment]
There have never been any versioned releases of TreeSheets, it's always been informally versioned by date of build, or commit, if you prefer.

The binaries on the site are simply the last build I happen to have made when I was working on said platform.

The ones in Linux distros are by commit id.

I personally don't like versions, as they are meaningless. There is no commit of TreeSheets that is any more or less release worthy than the others. There is no release branch, or any special testing that happens.

**Comment by baimafeima** [comment]
Tagging releases would have several advantages. Besides making the hangelog directly visible in your GitHub releases, it would increase transparency for potential users and distribution maintainers and version updates can be tracked more easily. Something like https://skywinder.github.io/github-changelog-generator/ could be used to generate the changelog based on merged PRs and closed issues since the last release tag.

**Comment by aardappel** [comment]
Look at: https://github.com/aardappel/treesheets/commits/master
It's mostly all small fixes. There's no meaningful changelog to derive from that unless I made a version change once a year or so, at the current rate. I really don't see the point.

If someone wants to be in charge of creating arbitrary "versions" after each couple of commits, I'd be happy to give them push access.

**Comment by Vaelatern** [comment]
@aardappel I'd be happy to push versions if nobody else will.

**Comment by aardappel** [comment]
@Vaelatern : thanks for the help! I've given you push access, don't abuse it :)

Whatever versioning scheme makes sense to you, though given that TreeSheets is pretty mature, we're definitely beyond 1.0

**Comment by Vaelatern** [comment]
@aardappel Unfortunately, when I try to push the tag, it doesn't work well.

```
└» git remote -v
origin  git@github.com:aardappel/treesheets.git (fetch)
origin  git@github.com:aardappel/treesheets.git (push)
└» git push origin v1.0.0
Host key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8
+---[RSA 2048]----+
| =+o...+=o..     |
|o++... *o .      |
|*.o.  *o.        |
|oo.  ..o.= .     |
|.+o. .. S =      |
|*=+ .  o = .     |
|OE .  . o        |
| o     .         |
|                 |
+----[SHA256]-----+
ERROR: Permission to aardappel/treesheets.git denied to Vaelatern.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

Do I actually have push rights here?

I chose v1.0.0 since it's a stable version, and semver is reasonably liked by people.

**Comment by aardappel** [comment]
I added you to the collaborators list, but it looks like you haven't accepted the invitation yet. Check your email for any emails from github :)

**Comment by Vaelatern** [comment]
Fantastic, thank you!
Issue closed with https://github.com/aardappel/treesheets/archive/v1.0.0.tar.gz
@Piraty
