### ISSUE TITLE
Crash when pressing F6 in new treesheet

### ISSUE THREAD

**Issue by dailymorn** [aardappel/treesheets#89]
Repro steps:

1. Launch TreeSheets.
1. Press Ctrl+N to create a new sheet.
1. New Sheet dialog is displayed.
1. Click OK in the New Sheet dialog.
1. Press F6.

Expected result: TreeSheets goes to a matching cell or does nothing.

Actual result: TreeSheets does a fatal application exit.

**Comment by aardappel** [comment]
Thanks for reporting! Just fixed here: https://github.com/aardappel/treesheets/commit/b3f6756c99b4896b5862ae482acd749e262d799d
