### ISSUE TITLE
"Size" value in bottom bar does not update until mouse is moved

### ISSUE THREAD

**Issue by gussmith23** [aardappel/treesheets#93]
Platform: Windows 10

Steps to reproduce:
1. Make a selection
2. Use shift+scroll wheel to increase or decrease the size of the selected cells while keeping the mouse still
3. Notice that the "Size" value in the bottom right does not change
4. Move the mouse; notice that the "Size" value changes.

**Comment by aardappel** [comment]
Hah, yes, it should probably update the status-bar when it changes size itself..

**Comment by learn-more** [comment]
This is now fixed.
