### ISSUE TITLE
idea: shift+enter inserts new child grid when none exists

### ISSUE THREAD

**Issue by gussmith23** [aardappel/treesheets#95]
Using shift+enter is a natural shortcut to selecting a cell's child grid. If a grid doesn't exist, I think it would be equally natural to have shift+enter create the child grid. Currently, without an INS key, inserting has to be done with the mouse. This would (possibly, depending on the application's design) be an easy way to resolve this complaint without implementing a key mapping system.

**Comment by aardappel** [comment]
I agree that would be a natural extension of the existing behavior.

**Comment by gussmith23** [comment]
By the way -- I intend to take a crack at some of these bugs I'm opening, seeing as I've opened a number of them now, haha. It may have to wait until the summer, when I'm more free. I'm thinking this might be my first one to take on (if someone doesn't take it first!)

**Comment by aardappel** [comment]
@gussmith23 that be appreciated :)

**Comment by aardappel** [comment]
Fixed by: https://github.com/aardappel/treesheets/pull/97

**Comment by gussmith23** [comment]
beautiful! thanks all!
