### ISSUE TITLE
ctrl+backspace to delete whole words 

### ISSUE THREAD

**Issue by gussmith23** [aardappel/treesheets#99]
If this is currently a feature, it doesn't work on Windows. It inserts this character: [""](https://www.fileformat.info/info/unicode/char/007f/index.htm) (DELETE character; I guess that makes sense!)

ctrl+backspace seems to be a pretty standard combo in other editors -- hoping it can be added here too!

**Comment by aardappel** [comment]
Yup, looks like that isn't implemented, and would make sense to be added.

**Comment by aardappel** [comment]
Fixed by: https://github.com/aardappel/treesheets/pull/138
